subconsciousnetwork/subconscious

xcode/Subconscious/Shared/Components/Notebook.swift

This PR adds a short log string for `NotebookAction.succeedSaveEntry` to keep the logs tidy.
Since Notebook intercepts `DetailAction.succeedSave` in order to refresh lists, we need to handle the log string at this level too.

Add short log string for succeedSaveEntry

---

xcode/Subconscious/Shared/Components/Common/Search.swift
xcode/Subconscious/Shared/Components/Feed.swift
xcode/Subconscious/Shared/Components/Notebook.swift
xcode/Subconscious/SubconsciousTests/Tests_Search.swift

Introduces 'SearchAction.hideAndClearQuery`, which hides the search and clears the query. Also add tests for search actions.
Fixes #343.

Clear search on submit

---

xcode/Subconscious/Shared/Components/Common/MarkupTextViewRepresentable.swift
xcode/Subconscious/Shared/Components/Common/StoryPromptView.swift
xcode/Subconscious/Shared/Components/Common/StoryView.swift
xcode/Subconscious/Shared/Components/Detail.swift
xcode/Subconscious/Shared/Components/Feed.swift
xcode/Subconscious/Shared/Components/Notebook.swift
xcode/Subconscious/Shared/Components/NotebookNavigationView.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift
xcode/Subconscious/SubconsciousTests/Tests_Detail.swift

This PR updates search-or-create actions to allow for the customization of fallback content that is distinct from the title of the note.
Previously we were using title as the fallback always, so these actions/APIs took a slug as a reference to the entry. This PR updates these actions/APIs to take an `EntryLink` instead, describing both a slug and a title. In some cases we continue to use entry title as fallback. However, adding this additional data to the APIs allows us to specify a title AND custom content if we wish.
This PR enables the work being done in https://github.com/subconsciousnetwork/subconscious/pull/340.

Allow custom fallback content

---

xcode/Subconscious/Shared/Components/Common/StoryComboView.swift
xcode/Subconscious/Shared/Components/Common/StoryView.swift
xcode/Subconscious/Shared/Config.swift
xcode/Subconscious/Shared/Data/Geists/combo.json
xcode/Subconscious/Shared/Data/Geists/zettelkasten.json
xcode/Subconscious/Shared/Models/Story.swift
xcode/Subconscious/Shared/Models/StoryCombo.swift
xcode/Subconscious/Shared/Services/ComboGeist.swift
xcode/Subconscious/Shared/SubconsciousApp.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj

Before trying to port my genetic algorithm over I figured it would be smart to take some baby steps. 
The intention of this PR is to introduce the `ComboGeist`, which randomly picks two entries and presents them together in the feed (screenshot attached).
I want to add a `Synthesize` action that would create a new entry _pre-populated_ with the `/slashlinks` to both the entries shown in the feed. I'm not quite sure how to do this as the current flow requires the user to enter a slug for the entry before reaching the editor. That's not a problem in-and-of-itself but we'd need to thread some context through to support the pre-populated editor content.
Keen to hear any suggestions for how to achieve this 😁

ComboGeist - randomly juxtapose two notes

---

xcode/Subconscious/Shared/Parsers/Subtext.swift
xcode/Subconscious/SubconsciousTests/Tests_Subtext.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/358.
We want to derive the excerpt from the first non-empty block.
Adds unit tests to test this behavior.

Return excerpt for first non-empty block

---

xcode/Subconscious/Shared/Library/FileSync.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift

Fixes #378
Still need to test a bit to make sure the rounded modified time (for sync) is still working as intended. Context there is that unless we round modified to nearest second, we tend to get funny business with sync due to difference in microtime.

Use file info as source of truth for modified/size

---

xcode/Subconscious/Shared/Services/DatabaseService.swift

Fixes #380
We have a new `description` column which contains a Subtext/plain text serialization of whatever the `body` is for search purposes. We accidentally didn't update our queries to use it. Fixed!

Fix backlink query

---

xcode/Subconscious/Shared/Components/Detail.swift

- Set title property, not linkable title
- Pass model, not state
Fixes #375

Fix update title after retitle

---

xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift

Ensures that the validation error icon will mask the text in the light and dark theme.
Extends https://github.com/subconsciousnetwork/subconscious/pull/398
Fixes #399

Fix ValidatedTextField badge background in dark theme

---

README.md

There are a few hoops to jump through when setting up for local device development, may as well document them for future devs.

Add instructions for development on-device

---

xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift

I forgot to update the base from `2023-02-17-color` to `main` before merging https://github.com/subconsciousnetwork/subconscious/pull/401, so it never made it into `main`. I'll blame the early starts for my brain not working.
This is the exact same change again, sorry for the runaround.
Fixes https://github.com/subconsciousnetwork/subconscious/issues/399

Fix ValidatedTextField background (again)

---

xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

This picks up changes from Noosphere@v0.6.3 which fix the saving/rollback bug we encountered in #397.
The v0.6.3 release branch Package.swift was incorrect, and points to the v0.6.2 build artifact. Therefore, we stay on Noosphere@main, which picks up the v0.6.3 build artifact.
Tested and confirmed that it resolves the saving problem.

Update Noosphere package

---

xcode/Subconscious/Shared/Components/Detail/Detail.swift
xcode/Subconscious/SubconsciousTests/Tests_Detail.swift

Fixes #409
Changes:
- The logic was simply missing for updating the DetailModel after a successful move or retitle. Added appropriate logic.
- Added regression tests that make sure title/address are updated when moving/retitling/merging.

Update detail after moving/retitling

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Settings/GatewayURLSettingsView.swift
xcode/Subconscious/Shared/Components/Settings/SettingsView.swift
xcode/Subconscious/Shared/Library/URLUtilities.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_URLUtiilities.swift
xcode/Subconscious/SubconsciousTests/Tests_URLUtilities.swift

Fixes #408 
Changes:
- Call `NoosphereService.resetGateway()` when a valid gateway URL is submitted in settings
- Configure gateway TextField for URLs
- Autocapitalize off
- Autocomplete off
- URL keyboard
- Introduce URL.isHTTP() extension, with tests.
- Limit labeled content in settings (including gateway URL field) to one line

Reset gateway when valid gateway URL is submitted in settings

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunCreateSphereView.swift
xcode/Subconscious/Shared/Components/FirstRun/RecoveryPhraseView.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_RecoveryPhrase.swift

We make RecoveryPhraseView a component that knows how to manage its own state and side-effects, when stitched into a larger component.
Fixes #400.
Introduces:
- RecoveryPhraseModel
- RecoveryPhraseAction
- AppRecoveryPhraseCursor to map from app domain to recovery phrase domain

Add copy/copied states to recovery phrase view

---

.gitattributes

This reduces the number of conflicts we get in pbxproj (Xcode project file) when merging multiple branches that touch the file.
Xcode project file merge conflicts are a perennial issue. In general, what you want is a union strategy for merging Xcode project files (keep both).
See https://roadfiresoftware.com/2015/09/automatically-resolving-git-merge-conflicts-in-xcodes-project-pbxproj/

Merge .pbxproj with union strategy

---

xcode/Subconscious/Shared/Components/BacklinksView.swift
xcode/Subconscious/Shared/Components/Common/EntryRow.swift
xcode/Subconscious/Shared/Components/Common/LinkSuggestionLabelView.swift
xcode/Subconscious/Shared/Components/Common/RenameSuggestionLabelView.swift
xcode/Subconscious/Shared/Components/Common/SlashlinkBarView.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryComboView.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryPromptView.swift
xcode/Subconscious/Shared/Components/Common/WikilinkBarView.swift
xcode/Subconscious/Shared/Components/Detail/Detail.swift
xcode/Subconscious/Shared/Components/Detail/DetailKeyboardToolbarView.swift
xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
xcode/Subconscious/Shared/Components/OmniboxView.swift
xcode/Subconscious/Shared/Components/RenameSearchView.swift
xcode/Subconscious/Shared/Models/Audience.swift
xcode/Subconscious/Shared/Models/EntryLink.swift
xcode/Subconscious/Shared/Models/MemoAddress.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_DataService.swift
xcode/Subconscious/SubconsciousTests/Tests_Detail.swift
xcode/Subconscious/SubconsciousTests/Tests_EntryLink.swift
xcode/Subconscious/SubconsciousTests/Tests_MemoAddress.swift
xcode/Subconscious/SubconsciousTests/Tests_NotebookUpdate.swift
xcode/Subconscious/SubconsciousTests/Tests_Search.swift

Previously MemoAddress was a struct containing an enum. This PR changes it to be an enum.
A local address should never have a petname, while a public address may have a petname (fully qualified e.g. @gordon/foo) or not (relative e.g. /foo).
Making the ID type itself an enum will alow us to smoothly evolve to a world where public posts can have fully qualified slashlinks.

Make MemoAddress an enum

---

xcode/Subconscious/Shared/Library/CollectionUtilities.swift
xcode/Subconscious/Shared/Parsers/Subtext.swift
xcode/Subconscious/Shared/Parsers/Tape.swift
xcode/Subconscious/SubconsciousTests/Tests_Subtext.swift

Introduces parsing for `@petname/slashlinks` in Subtext.
Fixes #385
Followup to #419.
Note that parsed slashlinks are simply identified in markup, not validated for correctness. To validate, parse through `Slashlink`.

Parse @petname/slashlinks in Subtext

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Settings/SettingsView.swift

There's currently no UI feedback for the gateway sync making it hard to tell if it worked as a user. This PR tracks the status of the sync operation in the `AppModel` and uses that to display a status icon next to the sync button in the `SettingsView`.
The `.inProgress` state is animated, because it's the little things...
https://user-images.githubusercontent.com/5009316/222312511-cdf83d69-9451-4f4f-99f3-a09ae639ab09.mov

Gateway Sync Status Indicator

---

xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift
xcode/Subconscious/Shared/Library/NSRangeUtilities.swift
xcode/Subconscious/Shared/Parsers/Subtext.swift

This renders attributes directly to TextStorage (like we used to but with TK2) to resolve #431
I've also put together a proof-of-concept for how we could do per-paragraph rendering in #433

Restore full-document attribute rendering

---

xcode/Subconscious/Shared/Components/Detail/Detail.swift
xcode/Subconscious/Shared/Components/OmniboxView.swift

Fixes #437. 
This PR introduces improvements to Omnibox:
- Displays specially formatted `@handles/slashlinks` when petname present
- Animates changes to location with fade animation
- Introduces an untitled state for empty notes

Improve omnibox with 3p @handles, animations, untitled state

---

xcode/Subconscious/Shared/AppTheme.swift
xcode/Subconscious/Shared/Components/Common/FAB.swift
xcode/Subconscious/Shared/Config.swift

Fixes #376 (by removing the shader). Confirmed that this works on iOS 16.3.1 on-device.
This PR replaces the old FAB button style with one based on the Subconscious brand mark. All colours and styles were referenced directly from our brand [styleguide](https://drive.google.com/drive/u/4/folders/1kZJ5svfLPBWSXVY9YWbexdclIYJi-QS9) including colour names etc.

Replace FAB Orb Shader with Gradient

---

xcode/Subconscious/Shared/AppTheme.swift
xcode/Subconscious/Shared/Components/AddressBook/AddressBookEntryView.swift
xcode/Subconscious/Shared/Components/AddressBook/AddressBookModel.swift
xcode/Subconscious/Shared/Components/AddressBook/AddressBookView.swift
xcode/Subconscious/Shared/Components/AddressBook/FollowUserView.swift
xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift
xcode/Subconscious/Shared/Components/Common/Transclude/TranscludeView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunProfileView.swift
xcode/Subconscious/Shared/Components/Settings/GatewayURLSettingsView.swift
xcode/Subconscious/Shared/Components/Settings/ProfileSettingsView.swift
xcode/Subconscious/Shared/Models/FormField.swift
xcode/Subconscious/Shared/Services/AddressBookService.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
xcode/Subconscious/Shared/Services/Noosphere/SphereFS.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_DataService.swift
xcode/Subconscious/SubconsciousTests/Tests_FormField.swift

Resolves #443
This PR integrates the Address Book UI from #420 with the underlying persistence layer via Noosphere.
- Right now we dismiss the form on submission but we need to keep it open to show errors
**Note**: Swipe to unfollow can remove the entry from the UI without mutating the underlying store

Noosphere Address Book FFI Stub

---

xcode/Subconscious/Shared/AppTheme.swift

The red-purple-cyan fab should be displayed in light mode. The pink-violet-cyan fab should be displayed in dark mode.
Also:
- Tweaked text style (brand black for pink-violet-cyan fab)
- Left shadows the same. I think it looks really good to allow the purple color to bleed into the white background.

Flip FAB light/dark style

---

xcode/Subconscious/Shared/Components/BacklinksView.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryComboView.swift
xcode/Subconscious/Shared/Components/Common/Transclude/Transclude2View.swift
xcode/Subconscious/Shared/Components/Common/Transclude/TranscludeButtonStyle.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj

Additionally, add background wash on tap.
Fixes #446.

Expand transclude hit area to include empty space

---

xcode/Subconscious/Shared/Parsers/Subtext.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/Subconscious.xcodeproj/xcshareddata/xcbaselines/B80057E727DC355E002C0129.xcbaseline/73DEAF14-78DE-4620-81A3-9232B506BA93.plist
xcode/Subconscious/Subconscious.xcodeproj/xcshareddata/xcbaselines/B80057E727DC355E002C0129.xcbaseline/Info.plist
xcode/Subconscious/SubconsciousTests/Tests_Subtext.swift
xcode/Subconscious/SubconsciousTests/Tests_SubtextAttributedStringRenderer.swift

Fixes #447.
This commit replaces the Regex-based matches with the old faster hand-rolled
recursive descent logic from https://github.com/subconsciousnetwork/subconscious/commit/16709dfa95a99d37c8ce53423e2f1a9e4c3a7c5a.
Profiling the newer regex-based Subtext parser logic against the old hand-rolled non-regex recursive descent logic revealed that the non-regex approach is 97% faster than regex approach (0.013s vs 0.381s). Not sure why regex is so slow here, but we can put up with the inconvenience of a hand-written recursive descent parser in exchange for the sizable perf win.
- Replaces subtext parsing logic with faster recursive descent logic from https://github.com/subconsciousnetwork/subconscious/commit/16709dfa95a99d37c8ce53423e2f1a9e4c3a7c5a
- Adds perf test and baseline
All tests …

Fix Subtext perf regression, add Subtext perf test and baseline

---

xcode/Subconscious/Shared/AppTheme.swift
xcode/Subconscious/Shared/Components/AddressBook/AddressBookModel.swift
xcode/Subconscious/Shared/Components/AddressBook/AddressBookView.swift
xcode/Subconscious/Shared/Components/AddressBook/FollowUserView.swift
xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Services/AddressBookService.swift
xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift
xcode/Subconscious/Shared/Services/Noosphere/SphereFS.swift
xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
xcode/Subconscious/SubconsciousTests/Tests_DataService.swift

This PR introduces support for reading and writing address book content from the local sphere. The `AddressBookService` is responsible for providing an abstraction over the underlying petname storage.
- Confirmation for unfollow
- Human readable errors
- Error alert popups
- Actual FFI calls
- Extracted C array -> Swift array utility
Resolves https://github.com/subconsciousnetwork/subconscious/issues/448
- https://www.avanderlee.com/swiftui/error-alert-presenting/

Integrate Address Book API

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
xcode/Subconscious/SubconsciousTests/Tests_Noosphere.swift
xcode/Subconscious/SubconsciousTests/Tests_Sphere.swift

Fixes #477.
Note: to lock in the Noosphere SHA, I updated to main, then took the SHA pointed to in `Package.resolved` and locked in the dependency at that SHA.

Update Noosphere and Sphere FFI wrapper

---

xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/TestUtilities.swift
xcode/Subconscious/SubconsciousTests/Tests_DataService.swift
xcode/Subconscious/SubconsciousTests/Tests_NoosphereService.swift

- Added `traverse(petname: String) throws -> Sphere` to `SphereProtocol`
- Add private `Sphere.init` that constructs a `Sphere` from an `ns_sphere_t`
- Add `testSphereTraversal` (skipped test) to demonstrate usage
Resolves https://github.com/subconsciousnetwork/subconscious/issues/483

Integrate traversal FFI calls into NoosphereService

---

xcode/Subconscious/Shared/Components/Common/Byline/SlashlinkBylineView.swift
xcode/Subconscious/Shared/Components/Common/SlashlinkBarView.swift
xcode/Subconscious/Shared/Components/Detail/MemoDetailDescription.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
xcode/Subconscious/Shared/Components/OmniboxView.swift
xcode/Subconscious/Shared/Models/MemoAddress.swift
xcode/Subconscious/Shared/Models/Petname.swift
xcode/Subconscious/Shared/Models/Slashlink.swift
xcode/Subconscious/Shared/Models/Slug.swift
xcode/Subconscious/Shared/Models/StoryCombo.swift
xcode/Subconscious/Shared/Services/AddressBookService.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
xcode/Subconscious/SubconsciousTests/Tests_NoosphereService.swift
xcode/Subconscious/SubconsciousTests/Tests_Petname.swift
xcode/Subconscious/SubconsciousTests/Tests_Slashlink.swift
xcode/Subconscious/SubconsciousTests/Tests_Slug.swift
xcode/Subconscious/SubconsciousTests/Tests_Sphere.swift

This refactor smooths a few sharp edges I encountered while working on #486. Mostly it makes the Noosphere APIs strongly typed instead of stringly typed.
- `Slashlink` now holds an actual `Petname?` and `Slug` instead of a string `petnamePart` and `slugPart`
- SphereProtocol APIs now receive and return actual `Slashlink`, `Slug`, and `Petname` instead of `String`
- Update `SphereProtocol` to include petname methods.
- `Sphere.read(slashlink:)` now automatically handles traversal if the slashlink contains a Petname.
-`slashlink:` is now a proper `Slashlink` enabling us to inspect its structure and choose to traverse or not. This was the motivation for these changes.

Refactor SphereProtocol to enable traverse on read

---

xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

- Lock in new commit
- Update `Sphere` wrapper class to defer to Noosphere traversal logic instead of attempting to implement on Swift side.

Update to Noosphere v0.8.2

---

xcode/Subconscious/Shared/Library/UserDefaultsProperty.swift
xcode/Subconscious/SubconsciousTests/Tests_UserDefaultProperty.swift

Fixes #487.
Previously, we were setting the initial value to the wrapped `default` value. What we should have been doing is reading from UserDefaults at construction, and passing that to our `CurrentValueSubject`. This PR fixes the problem.
This is what was causing our Noosphere flag to spontaneously turn itself off between runs.

Read initial UserDefaultsProperty value from UserDefaults

---

xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailMetaSheetView.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift
xcode/Subconscious/SubconsciousTests/Tests_MemoViewerDetailMetaSheet.swift

This PR picks up on the discussion I started in https://github.com/subconsciousnetwork/subconscious/pull/486#discussion_r1162195697.
> To me, it seems cleaner to use ShareLink here instead of copying to the clipboard. I think it's more idiomatic in iOS in general to go via the share sheet since it offers copy to pasteboard within it anyway & it's more directly useful for sending a link in an iMessage etc.
> This apple link looked promising for guidance but I can't load it right now because of an SSL error(!!): https://developer.apple.com/design/human-interface-guidelines/patterns/collaboration-and-sharing/
> We could expose a computed shareableLink property from the model to keep the logic from the .copyLink handler in the model, then use the MetaTableItemShareLinkView I implemented …

Use ShareLink for sharing links

---

xcode/Subconscious/Shared/Models/Petname.swift
xcode/Subconscious/Shared/Models/Slashlink.swift
xcode/Subconscious/SubconsciousTests/Tests_Petname.swift
xcode/Subconscious/SubconsciousTests/Tests_Slashlink.swift

- Allow dotted petnames
- Allow petname-only constructor for a Slashlink (i.e. @ben)
These changes render all forms of slashlink as clickable in the TextView.
```
/test
@ben
@ben/test/test/test
@ben.foo.bar/baz/qux
```

Allow @name-only Slashlinks and dotted Petnames

---

xcode/Subconscious/Shared/Components/AddressBook/AddressBookModel.swift
xcode/Subconscious/Shared/Components/AddressBook/AddressBookView.swift
xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Common/Forms/Search.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift
xcode/Subconscious/Shared/Components/Detail/RenameSearchView.swift
xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
xcode/Subconscious/Shared/Library/CombineUtilities.swift
xcode/Subconscious/Shared/Library/Func.swift
xcode/Subconscious/Shared/Services/AddressBookService.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/FeedService.swift
xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift
xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
xcode/Subconscious/SubconsciousTests/TestUtilities.swift
xcode/Subconscious/SubconsciousTests/Tests_CombineUtilities.swift
xcode/Subconscious/SubconsciousTests/Tests_DataService.swift
xcode/Subconscious/SubconsciousTests/Tests_Func.swift
xcode/Subconscious/SubconsciousTests/Tests_NoosphereService.swift
xcode/Subconscious/SubconsciousTests/Tests_Sphere.swift

Fixes #439 
There are a few places where we have inadvertently called Noosphere synchronously on the main thread, causing the UI to block on certain long operations, like syncing. This should never happen.
This PR fixes the issue, and makes services Swift `actor`s to make it difficult to trip over this footgun. Actors are isolated, and can only be accessed via async/await. This means you cannot accidentally call blocking synchronous APIs on an actor (as I found we were doing in a number of subtle places). You must await, or else wrap in some kind of callback or publisher. This prevents us from accidentally causing UI hangs.
- `NoosphereService`, `Noosphere` and `Sphere` are now Swift `actor`s. That means they always run off of the main thread, and are isolated (can only be accessed from …

Make all calls to Noosphere non-blocking on main thread

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Library/CombineUtilities.swift
xcode/Subconscious/Shared/Services/AddressBookService.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/FeedService.swift
xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift
xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
xcode/Subconscious/SubconsciousTests/Tests_CombineUtilities.swift

Tiny change, I kept getting compile errors using `Future.detached` because we had a typo!

Fix typo `detatched` -> `detached`

---

xcode/Subconscious/Shared/Services/AddressBookService.swift
xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift

Merging my work re-introduced some typos which broke the build on `main`. This PR fixes the build & will be the base of any future work on my end so this _should_ resolve the issue once and for all.

Fix stray typos

---

xcode/Subconscious/Shared/Components/Detail/UserProfileDetailMetaSheet.swift

`MemoAddress.toSlashlink()` is no longer an optional return value since https://github.com/subconsciousnetwork/subconscious/commit/db855e99657fbfbcaca3e04dd8b413d6694e52d2#diff-00211e56380835626ac7bd8af84a29b28e53c12b1d0298acef9588b2a942b83fR74.

Fix redundant unwrap

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunProfileView.swift
xcode/Subconscious/Shared/Config.swift
xcode/Subconscious/Shared/Services/AppDefaults.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift

...instead of user-provided nickname, when designating an owner key name. This value is not network-facing, and just needs to be something constistent across runs. Hard-coding avoids user input errors for value, and also avoids having to track changes to owner key name.
Fixes #540.

Use Config.noosphere.ownerKeyName constant

---

xcode/Subconscious/Shared/AppIcon.swift
xcode/Subconscious/Shared/Components/Common/Byline/PetnameBylineView.swift
xcode/Subconscious/Shared/Components/Common/Byline/SlashlinkBylineView.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryUserView.swift
xcode/Subconscious/Shared/Components/OmniboxView.swift

Fixes #541.
Also simplifying display style of location in bar. My sense is that petname parts should all have the same weight/color treatment, since they make up the "trust domain". This mirrors similar UI in browsers:

Fix Omnibox icon for various states

---

xcode/Subconscious/Shared/Services/DataService.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/553
This does not address the capitalisation of the slug, I'm not sure where we landed on that?
If the first line starts with a capital this will generate a slug with a capital letter but it seems like leaving and reloading the note causes it to become lowercase?

Use only the first line to generate entry title

---

xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Services/UserProfileService.swift
xcode/Subconscious/SubconsciousTests/Tests_UserProfileService.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/565
The entries were not sorted at all before. We still do not have an implementation for top entries, but we can probably build it after #323 lands.

Sort recent entries on profile by recency

---

xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
xcode/Subconscious/Shared/Services/UserProfileService.swift
xcode/Subconscious/SubconsciousTests/Tests_UserProfileService.swift

Fixes a bug that blocks us from loading profiles, I collapsed the two paths into one to ensure this particular edge-case cannot reoccur.
The actual issue was introduced by `NoosphereService.sphere(did: Did)`, opening a sphere this way DID seems to succeed but leads to null pointer errors down the line. I replaced it with `NoosphereService.sphere(address: MemoAddress)` which will call traverse when appropriate. 
This will need to be adjusted slightly in the wake of https://github.com/subconsciousnetwork/subconscious/pull/561

Simplify `UserProfileService`

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunView.swift
xcode/Subconscious/Shared/Components/Settings/GatewayURLSettingsView.swift
xcode/Subconscious/Shared/Components/Settings/SettingsView.swift
xcode/Subconscious/Shared/Config.swift
xcode/Subconscious/Shared/Library/Func.swift
xcode/Subconscious/Shared/Models/InviteCode.swift
xcode/Subconscious/Shared/Services/GatewayProvisioningService.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_Func.swift
xcode/Subconscious/SubconsciousTests/Tests_GatewayProvisioningService.swift

Resolves https://github.com/subconsciousnetwork/subconscious/issues/468
Resolves #533 
Call out to `cloudctl` to attempt to provision a gateway from within the app.
- Different icons for different states, extract component?

Provision Gateway during onboarding

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift
xcode/Subconscious/SubconsciousTests/Tests_DatabaseService.swift

This PR adds functions to:
- Index any followed sphere in database
- Purge any sphere by did from database
- Purge any sphere you follow by petname from database
This should give us the methods we need to implement indexing/purging on follow/unfollow. Note this PR only creates the methods, it does not yet implement indexing/purging in the app.
Precursor to #323 #363 #551 
TODO:

Index 3P spheres in DB

---

xcode/Subconscious/Shared/Components/Common/Audience/AudienceMenuButtonView.swift
xcode/Subconscious/Shared/Components/Common/Suggestion/SuggestionLabelView.swift
xcode/Subconscious/Shared/Models/Audience.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_Audience.swift

Fixes #605
While the domain model still thinks in "sphere" and "local" scopes, we use "public" and "draft" to refer to these concepts when speaking to the user. "Local" is an implementation detail. "Draft" more closely matches user intent (see #519).

Change user-facing instances of "local" to "draft"

---

xcode/Subconscious/Shared/Components/AppView.swift

Fixes #550 
This appears to be a longstanding bug in SwiftUI:
- https://stackoverflow.com/questions/58512344/swiftui-navigation-bar-button-not-clickable-after-sheet-has-been-presented
- https://stackoverflow.com/questions/60026248/swiftui-tap-target-for-navigation-bar-button-misaligned-after-dismissing-a-shee
The only fix that worked for me is https://stackoverflow.com/a/74631815 which is extremely hacky but works on-device.

Fix unresponsive toolbar icons

---

.github/workflows/swiftlint.yaml
.swiftlint.yml

Trying out a basic set of rules for catching mistakes like line length etc. everything is configured as a warning rather than an error right now so the build will never fail for lint reasons. I started with all the rules on and removed anything that was obviously in conflict with our existing style / rules.
We have ~500 lint warnings in the codebase atm and it would be good to fix them because github actions can only display a maximum of 10 linting errors per run (yeah, I know). So lint errors introduced in a PR won't actually show up in the UI until we clear the backlog of underlying lint issues. 
The github action I used (made by the author of Swiftlint) purports to be able to scope the linting to only files changed in the PR but I get errors whenever I try to configure it as per their …

Introduce Swiftlint

---

xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift

`getPetname` is a footgun, it only looks in the sphere's address book.
Fixes https://github.com/subconsciousnetwork/subconscious/issues/626

Correctly resolve second-order(+) petnames

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Models/Petname.swift
xcode/Subconscious/Shared/Services/AppDefaults.swift
xcode/Subconscious/Shared/Services/UserProfileService.swift
xcode/Subconscious/SubconsciousTests/Tests_UserProfileService.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/631
Fixes https://github.com/subconsciousnetwork/subconscious/issues/559
- Write to `_profile_` during onboarding so every user has a populated nickname
- Remove `AppDefaults.nickname`
Should we also remove the Nickname field in the settings? It seems superfluous. We _could_ allow access to the same "Edit Profile" form via the settings view (in addition to editing from the "your profile" view) but two ways to edit something sets off my design spidey sense.

Persist nickname in profile memo during onboarding

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Settings/GatewayURLSettingsView.swift

- Reset invite code field after gateway provisioning
- Prevent editing the invite code while provisioning
We clear the code in the case of failure or success because it is consumed upfront. We should persist the gateway ID separately to help with the unhappy path: https://github.com/subconsciousnetwork/subconscious/issues/643
Fixes https://github.com/subconsciousnetwork/subconscious/issues/607

Clear invite code after provisioning

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunDoneView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunProfileView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunRecoveryView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunSphereView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunView.swift

Moved the FirstRun navigation path into the store and used that to implement keyboard navigation. The diff is very noisy but most views are unchanged, just removed the wrapping NavigationStack from every step past the welcome view.
- Introduce `submitLabel` and `onSubmit` fields to `ValidatedTextField`
- Implement navigation using `onSubmit`
- Move `.createSphere` logic into the model
Fixes #620

Implement keyboard submit navigation in First Run

---

xcode/Subconscious/Shared/Components/Common/Profile/EditProfileSheet.swift
xcode/Subconscious/Shared/Library/URLUtilities.swift
xcode/Subconscious/SubconsciousTests/Tests_URLUtilities.swift

Introduce a new URL extension that is stricter than the default `URL(string:)` init. 
Fixes https://github.com/subconsciousnetwork/subconscious/issues/588
(Trivia: I generated this with copilot chat, including the tests! The tests failed at first but after telling it that it produced working code)

Introduce strict validation constructor for URL

---

xcode/Subconscious/Shared/Components/Common/Profile/EditProfileSheet.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileHeaderView.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryUserView.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Library/DummyDataUtilities.swift
xcode/Subconscious/Shared/Library/Prose.swift
xcode/Subconscious/Shared/Models/FormField.swift
xcode/Subconscious/Shared/Models/UserProfileBio.swift
xcode/Subconscious/Shared/Services/UserProfileService.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_UserProfileBio.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/587
- Bio is processed before reading or writing to change all whitespace to spaces & truncate at the max length
- Even with #647 users could still modify their profile to inject massive bio strings etc. 
- Remove line limit on bio editor, it makes life harder than it has to be

Process user profile bio before reading or writing JSON

---

xcode/Subconscious/Shared/Components/FirstRun/FirstRunProfileView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunView.swift

Gateway provisioning was broken because we tried to start it before we have the invite code. We should probably decouple the sphere creation and gateway provisioning further, but this fixes the immediate issue.

Wait to provision gateway until after we have the invite code

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Services/UserProfileService.swift

Builds on https://github.com/subconsciousnetwork/subconscious/pull/661
This was causing the profile to be trashed and recreated **whenever** the nickname changed regardless of whether the user already had a profile, erasing the bio. This explains a decent chunk of the weirdness we saw in playtesting.

Ensure `requestCreateInitialProfile` is idempotent

---

xcode/Subconscious/Shared/Components/FirstRun/FirstRunProfileView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunView.swift

This ensures it appears in blue:
Of the available options:
- done
- go
- send
- join
- route
- search
- return
- next
- continue
Only three are blue (that I've found anyway):
- done
- go
- search

Use `go` label for keyboard submit button

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Settings/GatewayURLSettingsView.swift
xcode/Subconscious/Shared/Services/AppDefaults.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/643
Explicitly record both the invite code and the gateway ID during provisioning. If the provisioning times out, the app crashes or the user loses connection etc. we can now pick up where we left off and check on our gateway.
I've confirmed that you can quit the app at any point during the lifecycle and resume it in a valid state.

Persist Gateway ID during provisioning

---

xcode/Subconscious/Shared/Components/Common/Profile/GenerativeProfilePic.swift

Fixes a bug in my RNG implementation that resulted in an incomplete random distribution.
Before:
After:

Fix seeded RNG implementation

---

xcode/Subconscious/Shared/Components/Settings/GatewayURLSettingsView.swift

Ignore the somewhat amusing invite code, look at the gateway ID:

Prevent gateway ID wrapping the line

---

xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/585
Use the address for navigation titles, this is more scannable anyway and avoids the problem of loading content in the background just to update the title.

Fix stale navigation titles

---

xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/683
When initially presented, the draft editor has no address associated with it (because the note lacks a title). Once the note has been saved (e.g. when leaving the view by tapping a slashlink) it now _has_ an address. When the draft editor's `.appear` action fired it incorrectly assumed it had no address and attempts to recreate the from scratch. We need to check if the `state.address` exists and use _that_ instead of the stale `description.address`.
h/t @gordonbrander for telling me to check the description logic 🙏 
Simple fix, subtle issue.

Ensure draft editor loads latest version of its content

---

xcode/Subconscious/Shared/Components/Common/Buttons/PillButtonStyle.swift
xcode/Subconscious/Shared/Components/Common/Byline/PetnameView.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileHeaderView.swift

Fixes #680 
Fixes #713 
- Truncate petname in the middle
- Reduce size of profile action button
- Do we want to shrink the buttons? We can probably get away with truncation but I feel like the buttons were a little large

Improve handling of long petnames

---

xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryUserView.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Services/AddressBookService.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/684
Fixes https://github.com/subconsciousnetwork/subconscious/issues/699
- Changed "unresolved" icon to be less prominent (screenshot below)
- Introduced "Refresh" option in context menu
- Sync with gateway when doing pull-to-refresh on profile
- Slightly increase wait duration for resolution

Profile refresh & resolution

---

.env.example
.gitignore
README.md
xcode/Subconscious/Shared/SubconsciousApp.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

We still need to upload debug symbols for release builds.

Report uncaught exceptions with sentry.io

---

xcode/Subconscious/Shared/Library/LogFmt.swift
xcode/Subconscious/Shared/Library/Sentry.swift
xcode/Subconscious/Shared/SubconsciousApp.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj

Extends #740 
Use `OSLogEnumerator` to pin the app logs to the reported error. This probably isn't super efficient but given the nature of reporting a crash, that's probably ok.

Decorate Sentry errors with log stream

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Settings/GatewayURLSettingsView.swift
xcode/Subconscious/Shared/Components/Settings/SettingsView.swift
xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift

Related to https://github.com/subconsciousnetwork/subconscious/issues/693
- Clarify gateway URL lifecycle
- Make updates to gateway URL idempotent
- Prevent editing key values during sync
Unsure if this technically "fixes" the issue, since we still reset our noosphere instance as-soon-as there's a reason to update the gateway URL. Perhaps we should be queuing the reset operation (somehow) until after in-flight work is complete? Or perhaps we can find a way to update the gateway URL without tearing down and rebuilding noosphere?

Make Gateway URL update idempotent

---

xcode/Subconscious/Shared/Components/OmniboxView.swift

Fixes #709 
It really seems like switching from `.onAppear` to `.task` is enough. I could speculate as to why, but the short answer must be a race condition between layout and animation that is resolved by the time a `.task` runs.
I can trigger the issue occasionally by spamming navigation with `.onAppear` but not with `.task`.

Fix loading bar animation

---

xcode/Subconscious/Shared/Library/Sentry.swift
xcode/Subconscious/Subconscious.xcodeproj/xcshareddata/xcschemes/Subconscious (iOS).xcscheme

Introduced a `TEST` environment variable only set when the `SubconsciousTests` scheme runs.

Disable Sentry logging while running tests

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Common/Byline/PetnameView.swift
xcode/Subconscious/Shared/Components/Common/Profile/EditProfileSheet.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileHeaderView.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryUserView.swift
xcode/Subconscious/Shared/Components/Common/SubtextView.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
xcode/Subconscious/Shared/Components/Notebook/NotebookNavigationView.swift
xcode/Subconscious/Shared/Library/DummyDataUtilities.swift
xcode/Subconscious/Shared/Library/Func.swift
xcode/Subconscious/Shared/Models/Slashlink.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift
xcode/Subconscious/Shared/Services/TranscludeService.swift
xcode/Subconscious/Shared/Services/UserProfileService.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/TestUtilities.swift
xcode/Subconscious/SubconsciousTests/Tests_TranscludeService.swift

Related to #328 
Resolves #324 
Fixes https://github.com/subconsciousnetwork/subconscious/issues/710
This approach is based on my experiments with rendering in the editor: #428 
- Detect slashlinks in subtext blocks
- Fetch transclude previews from the sphere index (SQLite)
- Display inline between blocks
- Translate addresses to match the context
- Tests for fetching local transcludes
- Difficult to construct a test for 3P content with transcludes
- Insert some notes
- Force indexing them
- Call `.fetchTranscludes` with expected links
- Try different owner values?

Render transclude blocks in MemoDetailViewer

---

xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift
xcode/Subconscious/Subconscious.xcodeproj/xcshareddata/xcschemes/Subconscious (iOS).xcscheme

Fixes #759 
Discovered using the `Address Sanitizer` diagnostic in Xcode, which I've left enabled in Debug.
We must explicitly zero-out the `pointee` field after this unsafe allocation, otherwise it could literally be pointing _anywhere_.

Fix memory santization error

---

xcode/Subconscious/Shared/Components/Common/EntryList/EntryListEmptyView.swift
xcode/Subconscious/Shared/Components/Common/EntryList/EntryListView.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj

Fixes #599
- Create group for EntryList views
- Break empty state out into separate view
- Wrap empty state in scrollview, implement refreshable
Creates an escape hatch, at least, if users run into https://github.com/subconsciousnetwork/subconscious/issues/723

Make notes empty state pull-to-refreshable

---

xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Services/AddressBookService.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/769
https://github.com/subconsciousnetwork/subconscious/assets/5009316/74cbe177-07a9-4763-acf0-63d7d770e383
- Is it better to:
1. mark collision as a validation error and force the user to pick a new name
2. replace the name with an available suffixed version _in the form_
3. dismiss the form and find a unique name in the background, adding a suffix if needed
I tried (1) first and liked it but currently we have (2). (3) seems like a hard sell without #333.
- Prevent overwriting petnames
- Surface overwrite petname error to UI
- Suggest a unique name if there is a collision

Prevent overwriting petnames via Follow User form

---

xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Noosphere v0.12.1 includes the new (and hopefully last breaking) changes to UCAN. The version we have now is a strong candidate for what will become UCAN 1.0.
You will need to create new spheres to try the update.

Update to swift-noosphere-v0.12.1

---

xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift

- Fix gap at the bottom of user profile TabView
- The loading state tab still said "Recent" but the loaded state said "Notes"

Minor fixup on TabView

---

xcode/Subconscious/Shared/Services/UserProfileService.swift

I introduced a regression in determining the `pending` resolution state during https://github.com/subconsciousnetwork/subconscious/pull/795. We need to check if a given user is pending resolution when building the list of "followed" users on a profile.

Restore pending state in following list

---

xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift
xcode/Subconscious/Shared/Components/Notebook/NotebookNavigationView.swift
xcode/Subconscious/Shared/Config.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_Config.swift
xcode/Subconscious/iOS/Development.xcconfig
xcode/Subconscious/iOS/Info.plist
xcode/Subconscious/iOS/Release.xcconfig

Fixes https://github.com/subconsciousnetwork/subconscious/issues/816
- Introduce Release.xcconfig and Developent.xcconfig (see https://developer.apple.com/documentation/xcode/adding-a-build-configuration-file-to-your-project)
- Assign each to their respective build targets
- Extract default geist DID & petname, feedback URL and cloudctl URL to config
- Read config via Info.plist substitution
- Tests assert that config can be read 
See https://nshipster.com/xcconfig/ for a more comprehensive breakdown.

Introduce xcconfig build variables based on environment (Release vs. Debug)

---

xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/724
Insert slashlinks for 3P content.

Insert slashlinks for content with a `peer` component

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Common/EllipsisLabelView.swift
xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryUserView.swift
xcode/Subconscious/Shared/Components/Settings/AuthorizationSettingsView.swift
xcode/Subconscious/Shared/Components/Settings/SettingsView.swift
xcode/Subconscious/Shared/Components/Settings/SphereSettingsView.swift
xcode/Subconscious/Shared/Config.swift
xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
xcode/Subconscious/SubconsciousTests/Tests_Sphere.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/815
Fixes https://github.com/subconsciousnetwork/subconscious/issues/495
https://github.com/subconsciousnetwork/subconscious/assets/5009316/144c6695-d6a5-4f17-99ed-77c8daa87082
- Add authorization FFI methods to `SphereProtocol` and implement on `Sphere`/`Noosphere`
- Tests for authorization methods
- Read Noosphere version from FFI
- Introduce new `Sphere Settings` section in `Settings`
- Another way to access your DID in shareable form, text and QR code
- Within `Sphere Settings`, introduce `Authorization Settings`
- Form to authorize a DID + name combination
- List of current authorizations
- Ability to revoke authorizations (revoking the root will throw an error)
- Error handling
- Convenient `ShareLink` with the auth …

Implement Authorization FFI

---

xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift
xcode/Subconscious/Shared/Components/Common/Profile/EditProfileSheet.swift
xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift
xcode/Subconscious/Shared/Components/Common/Profile/FollowUserSheet.swift
xcode/Subconscious/Shared/Components/Detail/RenameSearchView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunProfileView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunView.swift
xcode/Subconscious/Shared/Components/Settings/AuthorizationSettingsView.swift
xcode/Subconscious/Shared/Components/Settings/GatewayURLSettingsView.swift
xcode/Subconscious/Shared/Components/Settings/InviteCodeSettingsSection.swift
xcode/Subconscious/Shared/Components/Settings/ProfileSettingsView.swift
xcode/Subconscious/Shared/Models/FormField.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/796
Port the `RenameSearchView` input field to `ValidatedFormField`. Reworked how `caption` works on `ValidatedTextField` in the process.

Fix edit link field cursor behaviour

---

xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
xcode/Subconscious/Shared/Models/Slashlink.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/SubconsciousTests/Tests_DataService.swift
xcode/Subconscious/SubconsciousTests/Tests_Slashlink.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/836
You were right @gordonbrander, we were looking at `description` here. It was actually quite subtle, since Slashlink uses `description` to meet the `Identifiable` protocol we were treating local addresses as being _equal to_ public ones.
`Slashlink.description` preserves the old behaviour, `Slashlink.markup` strips the local prefix (`did:subconscious:local`) but `verbatim` and `verbatimMarkup` preserve the prefix. My logic is:
- Description is human readable and detail preserving
- Verbatim is case preserving and detail preserving
- Markup is designed to be rendered in UI and inserted into text

Use `Slashlink.verbatim` when changing audience

---

xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift

Relies on https://github.com/subconsciousnetwork/subconscious/pull/837
Fixes https://github.com/subconsciousnetwork/subconscious/issues/798
Prefer updated address to stale address after changing audience.
Interestingly, this _also_ fixes https://github.com/subconsciousnetwork/subconscious/issues/583

Fix stale audience in navigation stack

---

xcode/Subconscious/Shared/Models/EntryStub.swift
xcode/Subconscious/Shared/Services/UserProfileService.swift

We were _always_ reading the user's sphere to populate the list of notes on the profile. This PR introduces an optimisation to read notes from the DB index if we follow the user who's profile we're loading. 
Combining this with the existing cache of user profile metadata makes it practically instant to load any profile we follow.

Massively improve profile load times

---

xcode/Subconscious/Shared/Components/Common/Byline/BylineSmView.swift
xcode/Subconscious/Shared/Components/Common/Profile/EditProfileSheet.swift
xcode/Subconscious/Shared/Components/Common/Profile/ProfilePic.swift
xcode/Subconscious/Shared/Services/UserProfileService.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/830
If `pfp` is `.none` then the icon for "local" audience is used in its place.

Show draft icon as pfp for local transcludes

---

xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift
xcode/Subconscious/Shared/Services/UserProfileService.swift
xcode/Subconscious/SubconsciousTests/Tests_DatabaseService.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/851
Maybe not the cleanest API, we have to differentiate between the case where we are listing the _user's_ recent notes vs someone they follow. We should only include local drafts when dealing with _our_ content.

Exclude local drafts from recent memos list

---

xcode/Subconscious/Shared/Components/AppView.swift

...if it already exists. We only run this code when the sphere is first created, so in theory it should not ever overwrite the default geist petname entry. However, let's toggle the "don't overwrite" option for further safety.

Don't overwrite default Geist petname

---

xcode/Subconscious/Shared/Library/LogFmt.swift
xcode/Subconscious/SubconsciousTests/Tests_LogFmt.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/858
This has been a bit of an adventure. Things I've learned:
[`OSLogPrivacy`](https://developer.apple.com/documentation/os/oslogprivacy) does what we want already, masking sensitive values in release builds. It will only censor values when running on hardware and not connected to a debugging session. 
Additionally, anything which interpolates a _string_ or _object_ will be treated as `OSLogPrivacy.private`, logs containing static text and interpolating _numbers_ are treated as public. See https://developer.apple.com/documentation/os/logging/generating_log_messages_from_your_code#3665948
> The unified logging system uses privacy options to hide or show interpolated variables in a message. By default, the system doesn’t …

Logging, PII and Sentry

---

xcode/Subconscious/Shared/Services/UserProfileService.swift

`UserProfileService.loadEntries` was previously opening a sphere for the address on every turn of the for loop.
This PR fixes the logic so the sphere is only opened once, at beginning of function call.

Fix loadEntries so sphere is only opened once

---

xcode/Subconscious/Shared/Components/AppTabView.swift
xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
xcode/Subconscious/Shared/Components/Notebook/NotebookNavigationView.swift
xcode/Subconscious/Shared/Models/StoryUser.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_DetailStack.swift
xcode/Subconscious/SubconsciousTests/Tests_NotebookUpdate.swift

Porting the work from https://github.com/subconsciousnetwork/subconscious/pull/784, moving towards https://github.com/subconsciousnetwork/subconscious/issues/641 and https://github.com/subconsciousnetwork/subconscious/issues/322.
This PR extracts the `NavigationStack` logic from `NotebookNavigationView` and shifts it to the re-usable component `DetailStackView`. This is a drop-in replacement in terms of the user experience, a stepping stone towards introducing the profile and feed as app tabs (next PRs).
I also snuck a couple fixes to warnings in, sorry if the diff is slightly more confusing as a result.

Extract DetailStackView

---

xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/iOS/Development.xcconfig
xcode/Subconscious/iOS/Release.xcconfig

Customise bundle identifier based on whether we're building dev vs release.

Change bundle identifier via config

---

xcode/Subconscious/Shared/Components/Common/Layout/TabbedColumnView.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift
xcode/Subconscious/Shared/Components/Common/Tabs/TabButtonView.swift
xcode/Subconscious/Shared/Components/Feed.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/829
Fixes https://github.com/subconsciousnetwork/subconscious/issues/874
https://github.com/subconsciousnetwork/subconscious/assets/5009316/7b2a2bee-0a27-4064-b478-c38bd9be0ef8
- Entire profile is wrapped in `ScrollView`, no sticky header
- In the fullness of time we will re-introduce this idea via UIKit
- Profile tabs do not animation font-weight between selected and default appearance
- Remove `TabView` and replace with custom implementation
- We lose out on gestures to swipe between tabs but not a huge loss
- Re-style profile note list to match `Feed` style
- Changing bio no-longer leads to stuttering animation + broken profile layout

Rework profile layout 

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Common/Recovery/RecoveryModeExplainPanelView.swift
xcode/Subconscious/Shared/Components/Common/Recovery/RecoveryModeFormPanelView.swift
xcode/Subconscious/Shared/Components/Common/Recovery/RecoveryView.swift

Builds on #892 to address in https://github.com/subconsciousnetwork/subconscious/pull/892#discussion_r1336558463.
- Remove app dependency from recovery mode
- Pass down ViewStore from app level
Other changes:
- Clean up excess view dependencies. There were places where we were requiring passing down properties that the view already had access to through its store
- Move recovery mode presentation flag up to app level (it's an app level concern)
- Use NavigationStack for recovery flow (more appropriate)

Remove app dependency from recovery mode 

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift
xcode/Subconscious/Shared/Components/Notebook/Notebook.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/894
As of https://github.com/subconsciousnetwork/subconscious/pull/885 are currently swallowing the actions that should refresh the `NotebookView` inside `DetailStack`. I would normally replay the events from `DetailStack`'s store on the `Notebook` store _but_ we (seemingly) can't do this with a `ViewStore`, there's no `actions` publisher exposed.
Instead, I am listening for `.detailStack()` actions in the `NotebookView` and replaying those on the `App` store and _then_ replaying those actions on the `Notebook` store. 
It fixes the problem but feels janky to me, can you think of a better approach @gordonbrander?

Replay notebook DetailStack actions on app root

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift

Previously, we were reading the known sphere identity from the SQLite database. This is suboptimal for a couple reasons:
- The database is an index, not a source of truth, and can be thrown away and re-built at any time. 
- The source of truth for the known sphere identity is `AppDefaults.standard.sphereIdentity` (UserDefaults)
- We store the identity here upon sphere creation
- UserDefaults persist for the life of the app container
- Relying on the database meant we had to wait until database migration was complete before checking for recovery state.
This PR makes the following changes:
- Read known sphere identity from `AppDefaults.standard.sphereIdentity`
- Run recovery check as early as possible (`.start`)
Additionally, I added some logs to `NoosphereService` to make it clearer when …

Retrieve sphere ID from UserDefaults and run recovery check earlier

---

xcode/Subconscious/Shared/Library/Sentry.swift

@justinabrahms noticed that errors from development are showing up in the production stream on Sentry, this is confusing and noisy.
In dev, we do want to record crash events etc. but we should set the `environment` appropriately.

Mark Sentry events as "development" in development

---

xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift
xcode/Subconscious/SubconsciousTests/Tests_DatabaseService.swift

Working on https://github.com/subconsciousnetwork/subconscious/pull/912 I realised that merging notes was broken. 
The addresses for merge suggestions were not being relativized when retrieved from SQLite, so they had a `peer` of `.did()` which made `writeMemo` blow up thinking it couldn't write to that path.
I've changed `searchRenameSuggestions` to relativize addresses.

Fix merging notes

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Library/Sentry.swift
xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/MockErrorLoggingService.swift
xcode/Subconscious/SubconsciousTests/TestUtilities.swift
xcode/Subconscious/SubconsciousTests/Tests_CombineUtilities.swift
xcode/Subconscious/SubconsciousTests/Tests_DataService.swift
xcode/Subconscious/SubconsciousTests/Tests_NoosphereService.swift

Log errors generated by the FFI wrappers to Sentry.

Integrate NoosphereService with Sentry logging

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Services/AppDefaults.swift

Tested on simulator and confirmed it works. 
I think the app should actually default to the `.notebook` view on first run, because the feed is always empty.

Persist selected `AppTab` in `UserDefaults`

---

xcode/Subconscious/Shared/Components/AppUpgradeView.swift
xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/FirstRun/FIrstRunInviteView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunDoneView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunInviteView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunOrbitEffectView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunProfileView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunRecoveryView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunSphereView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunView.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_FirstRun.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/910
> (Informational) Welcome to subconscious [Next]
> (Informational) "Your sphere stores all your data" [Create sphere]
> (Sphere created) Show mnemonic [I've written it down]
> Nickname [Next]
> Invite code [Redeem]
- Extract invite code form to new `FirstRunInviteView` step
- Re-order steps based on above description
- Wait to `.createSphere` until the `FIrstRunSphereView` step is submitted
- Introduce a new visualization `FirstRunOrbitEffectView`
- Normalize spacing between all "FirstRun" type screens
- Reduce jank when showing/hiding logo based on keyboard focus
https://github.com/subconsciousnetwork/subconscious/assets/5009316/a19e58e8-81f9-4efc-a4ea-8ef37dc02e94

Re-arrange onboarding steps

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Services/DataService.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/927
We cannot always guarantee that the identity is available (or even exists) but we can make a best-effort to include the identity for debugging purposes.

Attempt to include the DID if `indexPeer` fails

---

xcode/Subconscious/Shared/Services/AddressBookService.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/928
These updates to the database interfere with indexing and can result in a desync between the truth and the `peer` table in SQLite. We should let the indexing process be the sole way that the DB is updated.

Fix stale peer record in SQLite

---

xcode/Subconscious/Shared/Components/Common/Forms/Search.swift
xcode/Subconscious/Shared/Components/Feed.swift
xcode/Subconscious/Shared/Components/Notebook/Notebook.swift

PR updates search view to use a ViewStore. In my playtesting, this significantly improves the perceived perf of type-ahead suggestions.
Why? I suspect this may have something to do with the way inputs work in SwiftUI. Perhaps the binding-style closer access that goes all the way up to store allows the input field to render text BEFORE the search view is invalidated by the parent.
Background:
- I've been bothered by the perceived performance of type-ahead search in the app.
- At first, I suspected this was due to SQLite full text search running up against large amounts of indexed peer content. So I tried searching only post titles instead of full text search.
- However, upon investigating the app container, it turned out I was searching across relatively low amounts of content
- SQLite was …

Update search to use ViewStore

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileSheets.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Components/Feed/Feed.swift
xcode/Subconscious/Shared/Components/Settings/DeveloperSettingsView.swift
xcode/Subconscious/Shared/Services/AddressBookService.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/UserProfileService.swift
xcode/Subconscious/SubconsciousTests/Tests_DataService.swift
xcode/Subconscious/SubconsciousTests/Tests_UserProfileService.swift

1. Index peers in serial, never concurrently (introduce `Task.yield()` between each peer)
2. Pass `sphere` reference around in `UserProfileService` to minimise excessive init/deinit
3. Prevent excessive profile refreshing
4. Prevent refreshing profile if it's already loading
5. Log each step of producing the profile view
6. Fix bug: we were loading the data for the entire profile view just to get our nickname on startup
None of these dramatically changed anything for me in testing but they do all incrementally improve performance.
Fixes #943

Index peers serially (and other performance enhancements)

---

xcode/Subconscious/Shared/Models/StoryUser.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_StoryUser.swift

We should not be including newlines in the text description of this type since these get logged and break up logging.
Fixes #948

Update StoryUser description to remove newlines

---

xcode/Subconscious/Shared/Components/OmniboxView.swift

Popping views off the stack could trigger `.task{}` again and double the speed of the animation.
Originally mentioned in https://github.com/subconsciousnetwork/subconscious/issues/940

Fix double speed loading animation

---

xcode/Subconscious/SubconsciousTests/Tests_DataService.swift

It's a useful experiment, but it can't run reliably as part of the full test suite.

Skip concurrent indexing test

---

xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift

Fixes #940 
Introduce new `MemoViewer` action `.refreshAll` that actually does the loading. `.appear` will only trigger loading if the address changes and the `MemoViewerDetailView` listens for `AppAction.succeedSyncSphereWithGateway` to trigger `.refreshAll`.
My thinking is that 3P content can only change after a sync, so that's the only explicit trigger we need.

Do not refresh viewer if content is indentical

---

xcode/Subconscious/Shared/Components/Common/EntryList/EntryListView.swift

Fixes #955 
Using `role: .destructive` causes the list to preemptively remove the row. However, at this stage we have not removed it, only staged the removal, resulting in an animation jank as the item jumps back.
Instead, we do not assign a role, but give the action a tint. This causes it to show up as a destructive action (visually), but stages the deletion, avoiding the animation until the item is actually removed.
https://github.com/subconsciousnetwork/subconscious/assets/58421/e70c0afd-bbff-4ceb-8977-b3c163ae51f2

Fix delete animation in notes list

---

xcode/Subconscious/Shared/UIKit/UIHostingView.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj

...a helper view that makes it easier to embed UIHostingControllers in a parent view. Pass a parent controller into the initalizer, along with the UIHostingController. It will add the UIHostingController to the parent controller, and remove the UIHostingController from the parent controller when the UIView is deinitialized.
This should make it easier for us to embed SwiftUI views in the block editor.
Part of epic #214.

Add UIHostingView

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/BacklinksView.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryEntryView.swift
xcode/Subconscious/Shared/Components/Common/SubtextView.swift
xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Components/Feed/FeedListView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunDoneView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunProfileView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunRecoveryView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunSphereView.swift
xcode/Subconscious/Shared/Components/Settings/SettingsView.swift
xcode/Subconscious/Shared/Components/Settings/SphereSettingsView.swift
xcode/Subconscious/Shared/Models/EntryStub.swift
xcode/Subconscious/Shared/Models/ResolvedAddress.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_DetailStack.swift

Fixes #957 
- Ensure DID is known at link traversal time
- Thread the DID through from whatever context the link is being tapped in, lets us skip `noosphere.resolve`
- Don't let `context` make its way to the `DetailStackModel`

Fix (possible) delay on tapping links

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Common/Byline/PetnameView.swift
xcode/Subconscious/Shared/Components/Common/Profile/Sheets/FollowNewUserFormSheet.swift
xcode/Subconscious/Shared/Components/Common/Profile/Sheets/FollowUserSheet.swift
xcode/Subconscious/Shared/Components/Common/Profile/Sheets/RenameUserSheet.swift
xcode/Subconscious/Shared/Components/Common/Profile/Sheets/UnfollowUserSheet.swift
xcode/Subconscious/Shared/Components/Common/Profile/Sheets/UserProfileDetailMetaSheet.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift
xcode/Subconscious/Shared/Components/Detail/DetailToolbarContent.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Components/OmniboxView.swift
xcode/Subconscious/Shared/Models/StoryEntry.swift
xcode/Subconscious/Shared/Models/StoryUser.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_DatabaseService.swift
xcode/Subconscious/SubconsciousTests/Tests_Detail.swift
xcode/Subconscious/SubconsciousTests/Tests_UserProfileDetailModel.swift

Improves https://github.com/subconsciousnetwork/subconscious/issues/989
Fixes https://github.com/subconsciousnetwork/subconscious/issues/946
Fixes https://github.com/subconsciousnetwork/subconscious/issues/977
This PR remodels the follow/unfollow/rename operations and refresh lifecycle. It also introduces support for indexing multiple peers that point to the same DID.
https://github.com/subconsciousnetwork/subconscious/assets/5009316/58541708-99e1-4975-b2c1-97f079c0c66b
I intend to refactor the "wait for petname resolution" logic and background jobs in general as a follow up in https://github.com/subconsciousnetwork/subconscious/pull/996

Index and purge peers by petname + rework follow / unfollow lifecycle

---

xcode/Subconscious/Shared/Components/AppView.swift

The app never notifies the user that sync failed (or that it succeeded for that matter) which would've made it easier to diagnose an issue @justinabrahms ran into today.
This also provides some feedback that a drag-to-refresh did something.

Notify on sync failure and success

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Deck/DeckView.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Components/Feed/Feed.swift
xcode/Subconscious/Shared/Components/HomeProfileView.swift
xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Fixes #1012.
Requires https://github.com/subconsciousnetwork/ObservableStore/pull/44 to land. Will leave this PR as a draft until we review + cut a new release for ObservableStore including this change.
It seems that logging behavior changed in XCode 15. Now strings and objects are masked private by default.
This change updates ObservableStore to a new version that logs actions at the public level by default. It also updates all of our stores to use ObservableStore's logger instead of logging on `onReceive`.

Fix action logging in XCode 15

---

xcode/Subconscious/Shared/Models/Slug.swift

Fixes #980 
`formatting:` drops deep slashlinks which is unsuitable for reading backlinks, we were not relying on this behaviour in any calls to `toSlug()` so I've updated the constructor within that helper.

Prefer basic Slug constructor for DB queries

---

xcode/Subconscious/Shared/Components/Common/Profile/Sheets/EditProfileSheet.swift
xcode/Subconscious/Shared/Components/Common/Profile/Sheets/FollowUserFormView.swift
xcode/Subconscious/Shared/Components/Common/Profile/Sheets/FollowUserSheet.swift
xcode/Subconscious/Shared/Components/Common/Recovery/RecoveryModeFormPanelView.swift
xcode/Subconscious/Shared/Components/Detail/RenameSearchView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunInviteView.swift
xcode/Subconscious/Shared/Components/FirstRun/FirstRunProfileView.swift
xcode/Subconscious/Shared/Components/Settings/AuthorizationSettingsView.swift
xcode/Subconscious/Shared/Components/Settings/GatewayURLSettingsView.swift
xcode/Subconscious/Shared/Components/Settings/InviteCodeSettingsSection.swift
xcode/Subconscious/Shared/Components/Settings/ProfileSettingsView.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift

It turns out when I refactored our form fields to use `ViewStore` I accidentally routed around the cursors which means some actions (like populating rename results) were not being dispatched.
I've restored cursors at every use site of `ValidatedFormField`.
Fixes https://github.com/subconsciousnetwork/subconscious/issues/992
Fixes https://github.com/subconsciousnetwork/subconscious/issues/1021

Fix edit link menu

---

xcode/Subconscious/Shared/Library/UserDefaultsProperty.swift

This overshadowed the parent generic, and was simply a mistake. It becomes an error in future versions of Swift.
Simple fix, remove the generic. It's specialized by the parent already.

Remove generic from UserDefaultsKey

---

xcode/Subconscious/Shared/Components/Settings/AdvancedSettingsView.swift
xcode/Subconscious/Shared/Components/Settings/SettingsView.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj

Having the recovery button so close to the developer settings feels a bit scary to me, like I might accidentally tap it. This is a rarely-needed feature, so I created an advanced settings pane and moved it there, including some explanatory help text.

Move recovery to Advanced settings pane

---

xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
xcode/Subconscious/Shared/UIKit/BlockEditor/BlockEditorModel.swift

Fixes #1041
Setup:
- Go to Settings > Developer > Block Editor, and turn on block editor.
Scenario 1:
- Create a new note or edit an existing note
- Type some text
- Swipe back
What should happen: note should be saved.
Scenario 2:
- Create a new note or edit an existing note
- Type some text
- Background the app
What should happen: note should be saved.

Block editor: save when editor is backgrounded or un-presented

---

xcode/Subconscious/Shared/Components/Common/EntryRow.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryEntryView.swift
xcode/Subconscious/Shared/Components/Common/SubtextView.swift
xcode/Subconscious/Shared/Components/Common/Transclude/TranscludeView.swift
xcode/Subconscious/Shared/Components/Deck/CardStackView.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift

Discovered a bug we introduced in #1006 while I was playtesting: tapping transcludes resulted in double rebasing. For example:
1. viewing `@gordon/test`
2. tap a transclude block for `@gordon/hello`
3. I go to `@gordon.gordon/hello`
We need to pass more context down to `SubtextView` so it can appropriately handle link taps (need rebasing) vs. transclude taps (do not need rebasing).

Fix transclude link rebasing

---

xcode/Subconscious/Shared/UIKit/BlockEditor/Appendix/Related/BlockEditorRelatedModel.swift
xcode/Subconscious/Shared/UIKit/BlockEditor/Appendix/Related/RelatedCell.swift
xcode/Subconscious/Shared/UIKit/BlockEditor/BlockEditorModel.swift
xcode/Subconscious/Shared/UIKit/BlockEditor/BlockEditorModelUpdate.swift
xcode/Subconscious/Shared/UIKit/BlockEditor/BlockEditorViewController.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj

Smooth out block editor loading state

---

xcode/Subconscious/Shared/UIKit/BlockEditor/Appendix/Related/BlockEditorRelatedModel.swift
xcode/Subconscious/Shared/UIKit/BlockEditor/BlockEditorModel.swift

Minor cleanup following #1043
- Remove loading state from related. We don't need it.
- Mark loading state `notFound` if editor fails to load
- Mark loading state in succeedLoadEditor, not in setEditor
Part of #214

Fix loading state for block editor

---

xcode/Subconscious/Shared/Components/MainToolbar.swift
xcode/Subconscious/Shared/Components/Settings/SettingsView.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/1031
- tap sync indicator to show settings
- surface sync failure in root settings view

Show settings when tapping sync indicator

---

xcode/Subconscious/Shared/Components/Settings/AuthorizationSettingsView.swift
xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
xcode/Subconscious/SubconsciousTests/Tests_Sphere.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/1060
- Fetch name of authorizations
- Render in list view
- Move to `.contextMenu` for revocation and sharing
https://github.com/subconsciousnetwork/subconscious/assets/5009316/ddb7206d-45b1-40bb-9cec-d891a41a55a8

Render names in authorization list

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Deck/DeckView.swift
xcode/Subconscious/Shared/Models/ActivityEvent.swift
xcode/Subconscious/Shared/Services/AddressBookService.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_DatabaseService.swift
xcode/Subconscious/SubconsciousTests/Tests_Migrations.swift

Trying not to over engineer anything here.
- Create a new `activity` SQLite table
- Log events we may be interested in responding to / surfacing:
- Swipe choices in Deck view (step towards https://github.com/subconsciousnetwork/subconscious/issues/1023)
- Follow / unfollow user actions
- Index complete + how many changes
As mentioned above, this is a step towards offering more sophisticated behaviour in the Deck view over multiple sessions but it could also let us offer an "activity" view in the app where you can see updates like "`@gordon` published 4 notes".
https://github.com/subconsciousnetwork/subconscious/assets/5009316/c05dbb91-d3fa-47b1-bdff-60081f8761a0

Log key activities in SQLite

---

xcode/Subconscious/Shared/Components/Common/EntryList/EntryListView.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift
xcode/Subconscious/Shared/Components/Deck/CardStackView.swift
xcode/Subconscious/Shared/Components/Deck/DeckView.swift
xcode/Subconscious/Shared/Components/HomeProfileView.swift
xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
xcode/Subconscious/Shared/Components/Notebook/NotebookNavigationView.swift
xcode/Subconscious/Shared/Library/AnimationUtilities.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/991
Pretty simple, using `ScrollReaderView` for iOS 16 support but we could clean this up a little using the newer iOS 17 APIs down the line.
- Tap tab button again to scroll to top of lists
- Move away from .enumerated()
https://github.com/subconsciousnetwork/subconscious/assets/5009316/ef31c136-a8f5-4465-ac4f-6c0c5b392140
https://github.com/subconsciousnetwork/subconscious/assets/5009316/0443cf7b-693e-4b6f-bd8d-d071e1f50c3e

Tap tab button again to scroll to top

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Settings/DeveloperSettingsView.swift
xcode/Subconscious/Shared/Library/NoosphereLogProxy.swift
xcode/Subconscious/Shared/Library/Sentry.swift
xcode/Subconscious/Shared/Services/AppDefaults.swift
xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift
xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
xcode/Subconscious/Shared/SubconsciousApp.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj

1. Allow user configuration of Noosphere log detail (persisted using AppDefaults)
2. Pipe `stdout` to a logger to capture Noosphere logs
This is per-process on iOS and you can see the result via Console.app
Intended to help with debugging https://github.com/subconsciousnetwork/subconscious/issues/1008

Allow user-configuration of Noosphere log detail

---

xcode/Subconscious/Shared/Components/Common/Story/StoryEntryView.swift

Fix gradient truncation on dark mode

---

xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift
xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetailMetaSheetView.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailMetaSheetView.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/871
- MVP quoting feature
https://github.com/subconsciousnetwork/subconscious/assets/5009316/a0b1f522-0cf0-476c-8a3d-959e382d3fca

"Quote in new note" action

---

xcode/Subconscious/Shared/Components/Common/Byline/PetnameView.swift
xcode/Subconscious/Shared/Components/Common/EllipsisLabelView.swift
xcode/Subconscious/Shared/Components/Common/EntryList/EntryListRowButtonStyle.swift
xcode/Subconscious/Shared/Components/Common/Layout/TabbedColumnView.swift
xcode/Subconscious/Shared/Components/Common/Profile/ProfileHeaderButtonStyle.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileHeaderView.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryEntryView.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryPlaceholderView.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryUserView.swift
xcode/Subconscious/Shared/Components/Common/Tabs/TabHeaderView.swift
xcode/Subconscious/Shared/Components/Deck/DeckTheme.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Components/HomeProfileView.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/1062
After much deliberation, I decided I actually do kinda like the full gradient experience on the profile.
I can see the argument for leaving the header with a solid colour background though (see the comment below).

Profile reskin to match Deck and Notebook

---

xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift
xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
xcode/Subconscious/SubconsciousTests/Tests_NoosphereService.swift

Our `findBestLink` function was not considering `Did.local` as a possibility. Updated the code + tests to cover these cases.
I found this in-app in two places:
1. tapping a draft in the deck view opens in the viewer (uneditable)
2. tapping a backlink to a draft (in the related notes section) opened the viewer

Fix: tapping links to drafts could (erroneously) open the viewer instead of the editor

---

xcode/Subconscious/Shared/Components/Common/EntryList/EntryListView.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryEntryView.swift
xcode/Subconscious/Shared/Components/Deck/CardStackView.swift
xcode/Subconscious/Shared/Components/Deck/Cards/CardView.swift
xcode/Subconscious/Shared/Components/Deck/Cards/PromptCardView.swift
xcode/Subconscious/Shared/Components/Deck/DeckNavigationView.swift
xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Components/Notebook/NotebookNavigationView.swift
xcode/Subconscious/Shared/Models/EntryStub.swift

Add a `.contextMenu` to all the major views to allow Quoting from everywhere.

Make "Quote" action available from everywhere

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Library/Sentry.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

I've followed the documentation (https://docs.sentry.io/platforms/apple/performance/) and it seems to be working when I examine the Sentry SDK logs, but no data in the dashboard yet. Maybe there's latency, I'll wait and see.

Enable sentry performance tracing integration

---

xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift
xcode/Subconscious/Shared/Components/Common/Transclude/TranscludeListView.swift

Greatly improves performance in the profile view for users with many notes.

Use LazyVStack for all unknown-length lists

---

xcode/Subconscious/Shared/Components/AppView.swift

We ran into an issue where some gateways failed to come online in production and we timed out waiting. We've fixed the backend issue since. The scenario is recoverable by a user opening their gateway settings and hitting the "Check Provisioning Status" button but we can try to auto-detect and resolve the issue too.
If a sync fails but we _do_ have a gateway ID then it means provisioning must have timed out in the past. 
In the MTG future the provisioning time should drop to near-instant hopefully making this even less of an issue.
@gordonbrander can you think of a better condition to detect this situation? The user has redeemed an invite code for a gateway but they _haven't_ received the gateway URL yet. It's still going to be set to `127.0.0.1:4443` for anyone hit by this.

Re-check gateway provisioning status if sync fails but we DO have a gateway ID

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Services/AppDefaults.swift

The fix I implemented in https://github.com/subconsciousnetwork/subconscious/pull/1094 works but it's triggered in scenarios it shouldn't be. There's no ill effect of running this too often but I'd rather be precise.

Narrow trigger condition to re-check provisioning status

---

xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift

While investigating https://github.com/subconsciousnetwork/subconscious/issues/1108 I profiled the `plainEditor()` and found it was extremely expensive on each keystroke. It's incredibly expensive to set the `.text` property on the underlying view and doing so can result in cursor desync. 
I suspect this is also responsible for https://github.com/subconsciousnetwork/subconscious/issues/566.
Setting `.text` frequently causes `updateUIView()` to take a LONG time (up to 400ms in debug mode) which means `isUIViewUpdating` stays true for a long time and we start dropping input events if the user is typing rapidly. This is what is responsible for the autocorrect cursor desync issue linked above and can be replicated by typing very fast into the simulator. It's harder to trigger in release, …

Editor performance improvements

---

xcode/Subconscious/Shared/Components/AICommentsView.swift
xcode/Subconscious/Shared/Components/CommentsView.swift
xcode/Subconscious/Shared/Components/Deck/DeckTheme.swift
xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetailMetaSheetView.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailMetaSheetView.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj

Fixes https://github.com/subconsciousnetwork/subconscious/issues/1085
- Implement deterministic hash for color across executions
- Add comments to editor and viewer
- Tapping a comment will open a new editor instance preloaded with the comment + address

Implement "comments" under notes

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Common/EntryList/EntryListView.swift
xcode/Subconscious/Shared/Components/Common/EntryRow.swift
xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift
xcode/Subconscious/Shared/Components/Common/Story/StoryEntryView.swift
xcode/Subconscious/Shared/Components/Deck/CardStackView.swift
xcode/Subconscious/Shared/Components/Deck/Cards/CardContentView.swift
xcode/Subconscious/Shared/Components/Deck/Cards/CardView.swift
xcode/Subconscious/Shared/Components/Deck/Cards/EntryCardView.swift
xcode/Subconscious/Shared/Components/Deck/Cards/PromptCardView.swift
xcode/Subconscious/Shared/Components/Deck/DeckNavigationView.swift
xcode/Subconscious/Shared/Components/Deck/DeckView.swift
xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
xcode/Subconscious/Shared/Components/Notebook/NotebookNavigationView.swift
xcode/Subconscious/Shared/Models/StoryEntry.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/UserLikesService.swift
xcode/Subconscious/Shared/Services/UserProfileService.swift
xcode/Subconscious/SubconsciousTests/TestUtilities.swift
xcode/Subconscious/SubconsciousTests/Tests_DataService.swift
xcode/Subconscious/SubconsciousTests/Tests_Slashlink.swift
xcode/Subconscious/SubconsciousTests/Tests_UserLikesService.swift

Follow on from https://github.com/subconsciousnetwork/subconscious/pull/1106
Introduces:
- Show liked status with a small heart in list views (notebook & profile)
- Add / remove likes from the list view context menu
- A new `EntryNotification` abstraction to encode the core set of actions that can be taken on a note
https://github.com/subconsciousnetwork/subconscious/assets/5009316/b4cc4bda-049f-4f62-9dcb-ae4ab8858be2

Add, remove and render likes in list views

---

xcode/Subconscious/Shared/Components/AICommentsView.swift
xcode/Subconscious/Shared/Components/Deck/DeckTheme.swift
xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift

- Reduce card height to account for prompt header
- Cards grew in height when we introduced prompts and they feel too tall to me now
- Make whitespace around like button consistent between viewer and editor
- Add user profile header to the viewer
- Optional addition, I felt myself craving it while browsing
- Comments inherit the note color
- Reduces noise + creates a sense of visual relatedness

Visual tweaks after playtesting

---

xcode/Subconscious/Shared/Services/UserProfileService.swift

Liking a note and then deleting it triggered a "Not Found" error on the profile view.
We should skip over unreadable likes rather than throwing.

Skip unloadable likes and unresolvable peers when reading user likes

---

xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift

I ran into some issues testing on-device even with the previous fix (https://github.com/subconsciousnetwork/subconscious/pull/1109) and decided to change approach to something far simpler.
In my testing this behaves correctly on-device with system autocomplete, swipe typing, inserting markup, copy, paste, cursor manipulation etc.

Suspend re-rendering to UITextView.text if it causing the change in the first place

---

xcode/Subconscious/Shared/Components/BacklinksView.swift
xcode/Subconscious/Shared/Components/Common/Transclude/TranscludeListView.swift
xcode/Subconscious/Shared/Components/Deck/DeckTheme.swift

Note colors can change between app restarts. Apparently I messed this up again even after trying to fix it in https://github.com/subconsciousnetwork/subconscious/pull/1114
The mistake was subtle, so I'll give myself a pass.

Fix unstable derived note colors

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Deck/DeckView.swift
xcode/Subconscious/Shared/Library/Sentry.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift
xcode/Subconscious/Shared/SubconsciousApp.swift
xcode/Subconscious/SubconsciousTests/Tests_DataService.swift

While testing 0.0.18 I noticed the app seemed slow to boot & laggy at times. I profiled it using the App Startup profiling, as well as SwiftUI and good old fashioned CPU profiling, found the main bottlenecks and removed them:
- Limit the number of rows read from the DB to populate the deck
- Remove Sentry profiling integration
- Turns out we have to pay more money for this and we can profile the app locally just fine for now
- Defer SentryIntegration.start()
For me this seems to cut down launch time by nearly a second in the simulator. Hopefully that carries over to a real device!

Reduce app startup time

---

xcode/Subconscious/Shared/Components/AppTabView.swift
xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Common/Profile/Sheets/FollowNewUserFormSheet.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Components/Discover/DiscoverActionButtonStyle.swift
xcode/Subconscious/Shared/Components/Discover/DiscoverNavigationView.swift
xcode/Subconscious/Shared/Components/Discover/DiscoverUserView.swift
xcode/Subconscious/Shared/Components/Discover/DiscoverView.swift
xcode/Subconscious/Shared/Components/Notebook/NotebookNavigationView.swift
xcode/Subconscious/Shared/Library/DummyDataUtilities.swift
xcode/Subconscious/Shared/Models/AssociateRecord.swift
xcode/Subconscious/Shared/Models/NeighborRecord.swift
xcode/Subconscious/Shared/Services/DataService.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift
xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
xcode/Subconscious/SubconsciousTests/Tests_DatabaseService.swift
xcode/Subconscious/SubconsciousTests/Tests_UserProfileDetailModel.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/1084
**We need to consider that neighbors won't be indexed retroactively unless we choose to re-index from sphere creation.**
- Introduce "Discover" tab
- Index peers-of-peers as `neighbor`s
- Populate discover view using neighbors
- Also list suggestions in "Add User" section (predicting user intent)
https://github.com/subconsciousnetwork/subconscious/assets/5009316/021db477-a12a-47b0-8b0d-0a45b6da7e71

Implement peer discovery

---

xcode/Subconscious/Shared/Components/AppView.swift
xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
xcode/Subconscious/Shared/Models/Memo.swift
xcode/Subconscious/Shared/Parsers/Tape.swift
xcode/Subconscious/Shared/Services/DataService.swift

- Batch reads and database calls in tight loops
- Reduce re-parsing cost in MemoRecord init
- Index peers in TaskGroup
- Reduce re-parsing again
- Adjust task priority
Speeds up indexing between 4x and 6x.
Before
After

Improve indexing performance

---

xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/1065
Fixes https://github.com/subconsciousnetwork/subconscious/issues/1100 (I think)
- Do not actually attempt to save a note unless it has been modified
- Cancel polling action once editor closes

Prevent runaway autosave polling + concurrent save attempts

---

xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift
xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
xcode/Subconscious/Shared/Services/Noosphere/SphereFile.swift
xcode/Subconscious/SubconsciousTests/Tests_Noosphere.swift
xcode/Subconscious/SubconsciousTests/Tests_Sphere.swift
xcode/Subconscious/SubconsciousTests/Tests_SphereFile.swift

As of XCode 15.3 (15E204a) we are getting a slew of new warnings about OpaquePointers in the Noosphere wrappers.
The problem stems from our Noosphere wrappers being individual actors, and OpaquePointers not being a sendable type (e.g. they should not cross state synchronization boundaries). That makes sense.
We implement Noosphere, Sphere, and SphereFile as actors because:
- We want to get Noosphere work off the main thread. Actors nudge code off the main thread
- Although this is not a hard guarantee of the green thread runtime IIRC, but it should do whatever it needs to do keep the main thread clear for UI.
- We want the state isolation and synchronization guarantees provided by an actor.
Since they're currently separate actors, we're passing OpaquePointers across actor boundaries. …

Isolate Noosphere wrappers to shared global actor

---

xcode/Subconscious/Shared/Components/Deck/DeckView.swift
xcode/Subconscious/Shared/Services/DatabaseService.swift
xcode/Subconscious/SubconsciousTests/Tests_DatabaseService.swift

Fixes https://github.com/subconsciousnetwork/subconscious/issues/1135
Drafts are only very rarely being drawn in the deck view but when it _does_ happen we were calculating the address incorrectly.
I relaxed the (old) constraint that preventing drafts from showing up in the deck view most of the time (I think you should be able to see these like any other note, otherwise they will never resurface) and clarified the address resolution when loading from SQLite.

Fix handling of draft addresses when loading from SQLite

---

xcode/Subconscious/Shared/Components/Common/MetaTableView.swift
xcode/Subconscious/Shared/Components/Common/RowButtonStyle.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailMetaSheetView.swift
xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift

Related to https://github.com/subconsciousnetwork/subconscious/issues/653
Introduces a "Share text" meta sheet action. I have been reaching for this functionality recently while going back and forth between my computer & phone.
**Consideration: do we want to remove "Share Link", it's unclear why you would want to copy the link outside the app until we have `http` URLs to pass around.**
https://github.com/subconsciousnetwork/subconscious/assets/5009316/153244b3-e9b8-4412-a4cd-22d9e9fa8370

Introduce metasheet action to share text
