subconsciousnetwork/subconscious

xcode/Subconscious/Shared/Components/Detail.swift, xcode/Subconscious/SubconsciousTests/Tests_Detail.swift
=> Request editor focus change when seting and presenting detail

xcode/Subconscious/Shared/Components/Common/Search.swift, xcode/Subconscious/SubconsciousTests/Tests_Search.swift
Clear text after animation complete using delayed fx. This causes less visual noise.
Also update tests.
Followup to #346.
=> Clear text after animation complete

xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
- Update version to 0.0.6
- Turn off Mac catalyst (it doesn't work properly yet)
=> Update version to 0.0.6 in project file

xcode/Subconscious/Shared/Components/Detail.swift
Detail editor now watches for scene phase change and invokes autosave when scene becomes inactive.
This fixes the case where you type some things, background the app (or force-quit the app), and the autosave timer doesn't get a chance to save the note before the app process is killed.
Fixes https://github.com/subconsciousnetwork/subconscious/issues/355
=> Save detail on scene phase change to inactive

xcode/Subconscious/Shared/Config.swift, xcode/Subconscious/Shared/Data/Geists/project.json, xcode/Subconscious/Shared/Services/DatabaseService.swift, xcode/Subconscious/Shared/SubconsciousApp.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
Asks questions about notes with "project" in their body.
Part of epic #16
=> Project Geist

xcode/Subconscious/Shared/Services/NoosphereService.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/SubconsciousTests/Tests_NoosphereService.swift
This PR introduces a Swift RAII wrapper for Noosphere.
- `Noosphere`, a class that manages the lifetime of the Noosphere pointer
- `Sphere`, a class that manages the lifetime of the sphere FS pointer, and exposes methods for reading, writing, saving
=> Noosphere Service

xcode/Subconscious/Shared/Services/NoosphereService.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, xcode/Subconscious/SubconsciousTests/Tests_AppMigrations.swift, xcode/Subconscious/SubconsciousTests/Tests_Entry.swift, xcode/Subconscious/SubconsciousTests/Tests_NoosphereFFI.swift, xcode/Subconscious/SubconsciousTests/Tests_Search.swift, xcode/Subconscious/SubconsciousTests/Tests_Sphere.swift
This PR updates the checked-out version of Noosphere used by Subconscious.
- Handle errors using new error out-parameter.
- Add version
- Add changes
- Add remove
- Add list
=> Update Noosphere wrapper to match new FFI

xcode/Subconscious/SubconsciousTests/Tests_DataService.swift
This test was written while we were troubleshooting the issue with Noosphere not flushing writes (fixed in https://github.com/subconsciousnetwork/noosphere/pull/231).
TLDR: this test was written to repro an issue with Noosphere losing data at a time when we were not sure where the issue was coming from. It should be updated to pass now.
At the time it was unclear where the issue was cropping up, so I wrote tests on the Subconscious side to repro.
We now know that before https://github.com/subconsciousnetwork/noosphere/pull/231, Noosphere was not flushing writes unless `ns_sphere_fs_free(fs)`, `ns_free(noosphere)` were called. We were calling these cleanup functions in the corresponding Swift wrapper class `deinit`. However, while `deinit` is always called in Swift, it is not guaranteed to …
=> Fix failing data service destructor test

xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
44f71e57918e0e8ca8d806db0aff82ff5ed0a5ba
=> Lock Noosphere at 0.0.7 SHA

xcode/Subconscious/Shared/Components/AddressBook/AddressBookModel.swift, xcode/Subconscious/Shared/Services/AddressBookService.swift
=> Guard against following yourself

xcode/Subconscious/Shared/Components/AppView.swift, xcode/Subconscious/Shared/Components/Detail/DetailMetaSheet.swift, xcode/Subconscious/Shared/Components/Settings/DeveloperSettingsView.swift, xcode/Subconscious/Shared/Components/Settings/SettingsView.swift, xcode/Subconscious/Shared/Library/UserDefaultsProperty.swift, xcode/Subconscious/Shared/Services/AppDefaults.swift, xcode/Subconscious/Shared/Services/DatabaseService.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/SubconsciousTests/Tests_App.swift, xcode/Subconscious/SubconsciousTests/Tests_UserDefaultProperty.swift
Fixes #471
Progress toward umbrella issue #472
=> Add developer setting to toggle Noosphere enabled

xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Update to latest version of the Swift package.
=> Update to noosphere 0.8.1

xcode/Subconscious/Shared/Components/Notebook/NotebookNavigationView.swift, xcode/Subconscious/Shared/Config.swift
Allow users to actually reach the address book so they can follow others and share their DID easily, enabling @cdata (and everyone else) to actually try multiplayer!
Feel free to merge on approval.
=> Remove `addressBook` flag, gate access behind Noosphere

xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift, xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift, xcode/Subconscious/Shared/Services/Noosphere/SphereFile.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, xcode/Subconscious/SubconsciousTests/Tests_SphereFile.swift
Fixes #510 
This PR implements the Noosphere 0.9.x non-blocking callback-based FFI. It wraps these APIs in async functions for ergonomic use.
=> Implement callback-based Noosphere FFI

xcode/Subconscious/Shared/Components/OmniboxView.swift
=> Always display lowercase address in Omnibox

xcode/Subconscious/Shared/Components/AppView.swift, xcode/Subconscious/Shared/Components/FirstRun/FirstRunProfileView.swift, xcode/Subconscious/Shared/Components/Settings/ProfileSettingsView.swift, xcode/Subconscious/SubconsciousTests/Tests_App.swift, xcode/Subconscious/SubconsciousTests/Tests_Petname.swift
=> Require valid nickname

xcode/Subconscious/Shared/Components/Common/Story/StoryEntryView.swift, xcode/Subconscious/Shared/Components/Common/Story/StoryUserView.swift
Background needs to be inside the button for it to count as tappable.
Fixes https://github.com/subconsciousnetwork/subconscious/issues/552
=> Fix tap targets for Story Views

xcode/Subconscious/Shared/AppTheme.swift, xcode/Subconscious/Shared/Components/Common/Profile/EditProfileSheet.swift, xcode/Subconscious/Shared/Components/Common/Profile/GenerativeProfilePic.swift, xcode/Subconscious/Shared/Components/Common/Profile/ProfilePic.swift, xcode/Subconscious/Shared/Components/Common/Profile/ProfilePicSm.swift, xcode/Subconscious/Shared/Components/Common/Story/StoryUserView.swift, xcode/Subconscious/Shared/Services/UserProfileService.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
Seeded based on the passed DID
=> Generative PFPs

xcode/Subconscious/Shared/Components/Common/Layout/ThreeColumnView.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift, xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift, xcode/Subconscious/Shared/Services/UserProfileService.swift
Placeholder UI until we have something useful to put here.
=> Replace "Top" tab with "Coming Soon..."

xcode/Subconscious/Shared/Components/AppView.swift, xcode/Subconscious/Shared/Models/Slashlink.swift, xcode/Subconscious/Shared/Services/DataService.swift, xcode/Subconscious/Shared/Services/DatabaseService.swift, xcode/Subconscious/SubconsciousTests/Tests_DataService.swift, xcode/Subconscious/SubconsciousTests/Tests_DatabaseService.swift, xcode/Subconscious/SubconsciousTests/Tests_Slashlink.swift
Fixes #580
Regression from #561.
=> Fix queries when Noosphere is off

xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
New version: e1021dc13c01cb270f59666ce153503c55aea1ce
Also update FFI function calls to match changes from https://github.com/subconsciousnetwork/noosphere/commit/41563288150725e87f3891abce15966220d92177
=> Update Noosphere to e1021dc1

xcode/Subconscious/Shared/Components/Detail/UserProfileDetailMetaSheet.swift
- Add divider to meta table
- Add large presentation detent to profile sheet
Fixes #602
Fixes #601
=> Fix profile bottom sheet styles

xcode/Subconscious/Shared/Components/AppUpgradeView.swift, xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift, xcode/Subconscious/Shared/Components/Common/Shapes/Line.swift, xcode/Subconscious/Shared/Components/FirstRun/FirstRunCreateSphereView.swift, xcode/Subconscious/Shared/Components/FirstRun/FirstRunDoneView.swift, xcode/Subconscious/Shared/Components/FirstRun/FirstRunProfileView.swift, xcode/Subconscious/Shared/Components/FirstRun/FirstRunRecoveryView.swift, xcode/Subconscious/Shared/Components/FirstRun/FirstRunSphereView.swift, xcode/Subconscious/Shared/Components/FirstRun/FirstRunView.swift, xcode/Subconscious/Shared/Components/Settings/GatewayURLSettingsView.swift, xcode/Subconscious/Shared/Components/Settings/SettingsView.swift, xcode/Subconscious/Shared/Components/StackedGlowingImage.swift, xcode/Subconscious/Shared/Models/FormField.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
> Story arc (FPO):
> 1. Subconscious is a place to garden thoughts and share them with others.
> 2. It’s powered by Noosphere, a decentralized protocol, so your data belongs to you.
> 3. This is your sphere. It stores your notes. (nickname)
> 4. Passphrase
> 5. Welcome to Subconscious (Begin) 
Fixes https://github.com/subconsciousnetwork/subconscious/issues/612
Fixes #513 
Fixes https://github.com/subconsciousnetwork/subconscious/issues/625
https://github.com/subconsciousnetwork/subconscious/assets/5009316/f6677bec-669d-41d5-9ff3-18db5add0aea
=> Onboarding copy pass

xcode/Subconscious/Shared/Components/Common/EmptyStateView.swift, xcode/Subconscious/Shared/Components/Common/Layout/ThreeColumnView.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileHeaderView.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
Fixes https://github.com/subconsciousnetwork/subconscious/issues/598
Fixes https://github.com/subconsciousnetwork/subconscious/issues/600
Reworked the structure to add empty states and make everything support `.refreshable{}`
https://github.com/subconsciousnetwork/subconscious/assets/5009316/b9f1ff2f-039e-4eb9-bfb9-cb592246aa13
=> Pull to refresh on profile

xcode/Subconscious/Shared/Components/AppView.swift, xcode/Subconscious/Shared/Components/FirstRun/RecoveryPhraseView.swift, xcode/Subconscious/SubconsciousTests/Tests_RecoveryPhrase.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/621
Copy is accessible via the share menu:
=> Replace Copy button with ShareLink

xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift, xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift, xcode/Subconscious/Shared/Services/UserProfileService.swift
- Created `.refresh()` helper that is used by the model and the UI
=> Wait for profile refresh to complete in `.refreshable {}`

xcode/Subconscious/Shared/Components/AppView.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift, xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift, xcode/Subconscious/Shared/Components/Notebook/Notebook.swift, xcode/Subconscious/Shared/Components/Notebook/NotebookNavigationView.swift
- Prevent access to JSON view of own profile
- Ensure nickname is populated
Fixes https://github.com/subconsciousnetwork/subconscious/issues/584
=> Prevent access to JSON profile editor

xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Switch to a tag reference instead of a SHA
=> Update to Noosphere 0.10.11

xcode/Subconscious/Shared/Components/AppView.swift, xcode/Subconscious/Shared/Services/UserProfileService.swift
Due to an oversight in https://github.com/subconsciousnetwork/subconscious/pull/662 we are truncating the nickname to only the first letter entered right now.
I hadn't realised that the nickname is saved on every keystroke, so my idempotent profile creation would create the profile immediately then never update it again. Instead, I've renamed the methods and updated the logic to always update the nickname but preserve the rest of the profile as-is. Y'know, actual idempotency.
=> Prevent nickname truncation during onboarding

xcode/Subconscious/Shared/Components/Common/EmptyStateView.swift, xcode/Subconscious/Shared/Components/Common/Layout/TabbedThreeColumnView.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileHeaderView.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift, xcode/Subconscious/Shared/Components/Common/Story/StoryPlaceholderView.swift, xcode/Subconscious/Shared/Components/Common/Story/StoryUserView.swift, xcode/Subconscious/Shared/Components/Common/Tabs/TabHeaderView.swift, xcode/Subconscious/Shared/Components/Detail/DetailToolbarContent.swift, xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift, xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift, xcode/Subconscious/Shared/Components/Notebook/Notebook.swift, xcode/Subconscious/Shared/Components/Notebook/NotebookNavigationView.swift, xcode/Subconscious/Shared/Components/OmniboxView.swift, xcode/Subconscious/Shared/Library/AnimationUtilities.swift, xcode/Subconscious/Shared/Services/UserProfileService.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
Fixes https://github.com/subconsciousnetwork/subconscious/issues/654
Fixes https://github.com/subconsciousnetwork/subconscious/issues/678
Fixes https://github.com/subconsciousnetwork/subconscious/issues/604
https://github.com/subconsciousnetwork/subconscious/assets/5009316/353b8fe8-e515-4d88-9bdc-2bd569ee9f64
- Pass partial profile data in description
- Display as much data as possible in loading state
- Add skeleton view
- Animate omnibar
=> Rich profile loading state

xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Fixes https://github.com/subconsciousnetwork/subconscious/issues/608
=> Update to noosphere@0.11.1

xcode/Subconscious/Shared/Components/Common/NotFoundView.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift, xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift, xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
Fixes https://github.com/subconsciousnetwork/subconscious/issues/690
=> Improve "Not Found" state

xcode/Subconscious/Shared/Components/Common/Profile/EditProfileSheet.swift, xcode/Subconscious/Shared/Components/Common/Profile/ProfilePic.swift, xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift, xcode/Subconscious/Shared/Services/UserProfileService.swift, xcode/Subconscious/SubconsciousTests/Tests_UserProfileService.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/712
- Remove the `ProfilePicVariant` case
- Remove validation code
- Remove form fields
=> Remove URL pfp option

xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
Fixes #734
Believe it or not, this fixes #734. It seems the reason for the crash is a bug in the Swift compiler. That switch statement, with all its arms, was just too much for the compiler to handle for some reason. Breaking out the arms into separate static methods and calling out to them seems to resolve the issue.
I have some speculation as to why that might be in #734, but really it's just staring at shadows on cave walls and making up stories.
My takeaway is that we should be breaking functions into bite-sized chunks so as not to scare the compiler. It tripped up over something different, but relating to complex Combine types back in #22 #60. It seems easy to spook.
=> Break UserProfileDetailView update functions out

xcode/Subconscious/Shared/Components/AppView.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/743
=> Update gateway URL input after submission

xcode/Subconscious/Shared/Components/AppView.swift, xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/741
=> Prevent logging mnemonic

xcode/Subconscious/Shared/Components/AppView.swift, xcode/Subconscious/Shared/Components/Detail/MemoEditorDetailMetaSheetView.swift, xcode/Subconscious/Shared/Components/Notebook/Notebook.swift, xcode/Subconscious/Shared/Components/Settings/DeveloperSettingsView.swift, xcode/Subconscious/Shared/Components/Settings/SettingsView.swift, xcode/Subconscious/Shared/Config.swift, xcode/Subconscious/Shared/Services/AppDefaults.swift, xcode/Subconscious/Shared/Services/DatabaseService.swift, xcode/Subconscious/SubconsciousTests/Tests_App.swift, xcode/Subconscious/SubconsciousTests/Tests_NotebookUpdate.swift
We want Noosphere to be always-on for Beta.
Fixes #729
=> Remove Noosphere feature flag

xcode/Subconscious/Shared/Components/Settings/SettingsView.swift, xcode/Subconscious/Shared/Config.swift, xcode/Subconscious/Shared/Library/BundleUtilities.swift
=> Settings: add app ver, build #, Noosphere ver

xcode/Subconscious/Shared/Components/Notebook/Notebook.swift, xcode/Subconscious/Shared/Components/OmniboxView.swift, xcode/Subconscious/Shared/Models/Slug.swift, xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift, xcode/Subconscious/SubconsciousTests/Tests_DatabaseService.swift, xcode/Subconscious/SubconsciousTests/Tests_Slug.swift
- Introduce `Slug.init(hidden:)`
- Introduce `Slug.init(visible:)`
- Strip leading `_` in `Slug.format`
- Refresh note count after new note creation
- Add tests to assert behaviour
=> Improve handling of hidden slugs

xcode/Subconscious/Shared/Services/ComboGeist.swift, xcode/Subconscious/Shared/Services/DataService.swift, xcode/Subconscious/Shared/Services/DatabaseService.swift, xcode/Subconscious/Shared/Services/MementoGeist.swift, xcode/Subconscious/Shared/Services/QueryPromptGeist.swift, xcode/Subconscious/Shared/Services/RandomPromptGeist.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/726
Fixes https://github.com/subconsciousnetwork/subconscious/issues/725
- Tweak loading animation trigger
- Fix random retrieval functions
I had to touch some of the old geist code but I just got it compiling and left them for now.
=> Fix "Random Note" suggestion

xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift, xcode/Subconscious/Shared/Services/DatabaseService.swift, xcode/Subconscious/Shared/Services/TranscludeService.swift
Since we merged https://github.com/subconsciousnetwork/subconscious/pull/574 for playtesting this PR addresses the formatting and small fixups from @gordonbrander's review.
=> Transclude blocks: fast follow fixes

xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
Fixes #723
About as simple as it gets!
=> Refresh notebook view after indexing

xcode/Subconscious/Shared/Components/Common/EntryList/EntryListView.swift, xcode/Subconscious/Shared/Components/Common/FabSpacerView.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
Prevent list items overlapping FAB on profile. 
Fixes https://github.com/subconsciousnetwork/subconscious/issues/771
=> Add spacing to prevent FAB overlap on profile

xcode/Subconscious/Shared/Components/Common/DidView.swift, xcode/Subconscious/Shared/Components/Common/Profile/DidQrCodeView.swift, xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift
Fixes #764 
Fixes #499 
- Break apart DidQrCodeView
- Implement copyable QR code
=> Make QR Code shareable

xcode/Subconscious/Shared/Components/Common/Profile/ProfileHeaderButtonStyle.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileHeaderView.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
Move profile action button down below bio.
Fixes #772 
- Introduced `ProfileHeaderButtonStyle`
=> Relocate profile action button

xcode/Subconscious/Shared/Components/BacklinksView.swift
...in user-facing text.
Fixes #739
=> Update "backlinks" to "related notes"

xcode/Subconscious/Shared/Components/Common/Profile/EditProfileSheet.swift, xcode/Subconscious/Shared/Components/Common/Profile/FollowUserFormSheet.swift, xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/833
Fixes https://github.com/subconsciousnetwork/subconscious/issues/826
- Disable "Done" buttons when form is invalid
- Optimistically hide "Edit Profile" sheet
=> Improve sheet "Done" button behaviour

xcode/Subconscious/Shared/Components/Common/Layout/TabbedColumnView.swift, xcode/Subconscious/Shared/Components/Common/Tabs/TabButtonView.swift, xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/825
- Fix hit target
- Drop superfluous VStack
=> Fix profile tab tap targets

xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Fixes https://github.com/subconsciousnetwork/subconscious/issues/848
=> Update to Noosphere 0.14.0

xcode/Subconscious/Shared/Components/Common/Profile/FollowUserSheet.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/827
Changed from custom `.fraction(0.33)` to `.medium` detent to support the smaller screen sizes (see issue). While I was at it I decided to remove the DID and put a preview in its place. I think this is a more economical use of space.
https://github.com/subconsciousnetwork/subconscious/assets/5009316/cfc4982c-d22b-4da7-b5fb-f1436b0010ab
=> Rework follow sheet layout

xcode/Subconscious/iOS/Development.xcconfig, xcode/Subconscious/iOS/Release.xcconfig
Sphere DID: `did:key:z6MkfUzJYTBW8Q7mwCvKbVjzBt5LvEPRbpZ3Ni7aZZZekMat`
=> Update Subconscious Geist sphere

xcode/Subconscious/Shared/Components/Detail/UserProfileDetailMetaSheet.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/876
=> Allow sharing QR code from profile metasheet

xcode/Subconscious/Shared/Components/Common/Byline/PetnameView.swift, xcode/Subconscious/Shared/Components/Common/Profile/EditProfileSheet.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileHeaderView.swift, xcode/Subconscious/Shared/Components/Common/Story/StoryUserView.swift, xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift, xcode/Subconscious/Shared/Library/DummyDataUtilities.swift, xcode/Subconscious/Shared/Services/AddressBookService.swift, xcode/Subconscious/Shared/Services/UserProfileService.swift, xcode/Subconscious/SubconsciousTests/Tests_AddressBookService.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/767
Before:
After:
=> Introduce `expectedName` for following status

xcode/Subconscious/Shared/Components/AppView.swift, xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/901
Fixes https://github.com/subconsciousnetwork/subconscious/issues/900
- Hide settings sheet when entering recovery
- Refresh notebook view after recovery
=> Recovery mode fixup

xcode/Subconscious/Shared/Components/AppTabView.swift, xcode/Subconscious/Shared/Components/AppView.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileHeaderView.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift, xcode/Subconscious/Shared/Components/Common/Story/StoryPlaceholderView.swift, xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift, xcode/Subconscious/Shared/Components/HomeProfileView.swift, xcode/Subconscious/Shared/Components/MainToolbar.swift, xcode/Subconscious/Shared/Components/Notebook/Notebook.swift, xcode/Subconscious/Shared/Components/Settings/DeveloperSettingsView.swift, xcode/Subconscious/Shared/Services/AppDefaults.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
Fixes https://github.com/subconsciousnetwork/subconscious/issues/641
- Introduce new Profile app tab
- Enable app tabs by default, remove feature toggle
- Add loading placeholder view for profile header
Added a loading placeholder for the header.
The "Add User" button no longer fits in the toolbar if the Settings icon is present. I tried moving it to the left side but then it interferes with the navigation "back" button. I think moving it to a more obvious location (vs burying in a dropdown menu) might be a good idea but I'm not in love with how it looks.
=> Introduce Profile tab

xcode/Subconscious/Shared/Components/AppView.swift, xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
I'm paranoid after experiencing https://github.com/subconsciousnetwork/subconscious/issues/902 so I did a pass over our most complex models and extracted any switch-case bodies to simplify typechecking.
=> Extract stray switch-case bodies to functions

xcode/Subconscious/Shared/Components/Common/Recovery/RecoveryModeFormPanelView.swift, xcode/Subconscious/Shared/Components/Common/Recovery/RecoveryView.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/SubconsciousTests/Tests_RecoveryMode.swift, xcode/Subconscious/SubconsciousTests/Tests_RecoveryModeView.swift, xcode/Subconscious/SubconsciousTests/Tests_RecoveryPhrase.swift, xcode/Subconscious/SubconsciousTests/Tests_RecoveryPhraseView.swift
PR implementing suggestion from https://github.com/subconsciousnetwork/subconscious/pull/913/files#r1341547372
Improves upon #913 by factoring out recovery button logic and adding tests.
=> Update #913 factoring out recovery button update fn and tests

xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift, xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailMetaSheetView.swift, xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift, xcode/Subconscious/SubconsciousTests/Tests_MemoViewerDetailMetaSheet.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/634
- View author profile from memo viewer metasheet
=> View author profile from metasheet

xcode/Subconscious/Shared/Components/Common/ExpandAlignedLeadingViewModifier.swift, xcode/Subconscious/Shared/Components/Common/SubtextView.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/873
=> Set size of spacer in expandAlignedLeading to 0

xcode/Subconscious/Shared/Components/Common/EllipsisLabelView.swift, xcode/Subconscious/Shared/Components/Common/EmptyStateView.swift, xcode/Subconscious/Shared/Components/Common/EntryRow.swift, xcode/Subconscious/Shared/Components/Common/Layout/TabbedColumnView.swift, xcode/Subconscious/Shared/Components/Common/Profile/UserProfileView.swift, xcode/Subconscious/Shared/Components/Common/Story/RectangleCroppedTopRightCorner.swift, xcode/Subconscious/Shared/Components/Common/Story/StoryEntryView.swift, xcode/Subconscious/Shared/Components/Common/Story/StoryPlaceholderView.swift, xcode/Subconscious/Shared/Components/Common/Story/StoryUserView.swift, xcode/Subconscious/Shared/Components/Common/SubtextView.swift, xcode/Subconscious/Shared/Components/Common/Tabs/TabHeaderView.swift, xcode/Subconscious/Shared/Components/Common/Transclude/TranscludeView.swift, xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift, xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift, xcode/Subconscious/Shared/Components/Detail/UserProfileDetailView.swift, xcode/Subconscious/Shared/Components/Feed.swift, xcode/Subconscious/Shared/Components/Feed/Feed.swift, xcode/Subconscious/Shared/Components/Feed/FeedEmptyView.swift, xcode/Subconscious/Shared/Components/Feed/FeedListView.swift, xcode/Subconscious/Shared/Components/Feed/FeedPlaceholderView.swift, xcode/Subconscious/Shared/Components/HomeProfileView.swift, xcode/Subconscious/Shared/Models/StoryEntry.swift, xcode/Subconscious/Shared/Parsers/Subtext.swift, xcode/Subconscious/Shared/Services/DataService.swift, xcode/Subconscious/Shared/Services/UserProfileService.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/SubconsciousTests/Tests_DetailStack.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/897
Fixes https://github.com/subconsciousnetwork/subconscious/issues/804
- Implement updated story styles
- Catch user profile loading error
- Add (missing) FAB to profile tab
- Render subtext in excerpts
- Allow tapping slashlinks in excerpts of feed posts
https://github.com/subconsciousnetwork/subconscious/assets/5009316/e08f9c13-efea-449a-ab3a-eed4ee21f10c
- https://github.com/subconsciousnetwork/subconscious/issues/926
=> Updated feed & profile post styles

xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Playtesting blocked by stormy network conditions but the tests pass.
=> Update to Noosphere 0.15.3

xcode/Subconscious/Shared/Components/AppView.swift
If DEBUG, set academic, otherwise basic.
Fixes #949.
=> Set NoosphereService log level depending on DEBUG

xcode/Subconscious/Shared/Components/Common/ErrorDetailView.swift, xcode/Subconscious/Shared/Components/Common/Recovery/RecoveryModeExplainPanelView.swift, xcode/Subconscious/Shared/Components/Common/Recovery/RecoveryModeFormPanelView.swift
=> Recovery mode refinements

xcode/Subconscious/Shared/Components/Common/ErrorDetailView.swift, xcode/Subconscious/Shared/Components/Common/Forms/ValidatedTextField.swift, xcode/Subconscious/Shared/Components/Common/Recovery/RecoveryModeExplainPanelView.swift, xcode/Subconscious/Shared/Components/Common/Recovery/RecoveryModeFormPanelView.swift, xcode/Subconscious/Shared/Components/Common/Recovery/RecoveryView.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/963
Fixes https://github.com/subconsciousnetwork/subconscious/issues/964
Fixes https://github.com/subconsciousnetwork/subconscious/issues/965
=> Recovery mode improvements

xcode/Subconscious/Shared/Components/BacklinksView.swift, xcode/Subconscious/Shared/Components/Common/Byline/BylineSmView.swift, xcode/Subconscious/Shared/Components/Common/Profile/ProfilePic.swift
=> Display empty circle glyph for local did

xcode/Subconscious/Shared/Components/Common/EntryList/EntryListView.swift, xcode/Subconscious/Shared/Components/Common/RowViewModifier.swift
Balances the swipe actions in the notes row.
=> Adjust row insets

xcode/Subconscious/Shared/AppTheme.swift, xcode/Subconscious/Shared/Components/AppTabView.swift, xcode/Subconscious/Shared/Components/AppView.swift, xcode/Subconscious/Shared/Components/Common/Byline/BylineSmView.swift, xcode/Subconscious/Shared/Components/Common/CountChip.swift, xcode/Subconscious/Shared/Components/Common/EntryList/EntryListRowButtonStyle.swift, xcode/Subconscious/Shared/Components/Common/EntryList/EntryListView.swift, xcode/Subconscious/Shared/Components/Common/EntryRow.swift, xcode/Subconscious/Shared/Components/Common/RowViewModifier.swift, xcode/Subconscious/Shared/Components/Common/SubtextView.swift, xcode/Subconscious/Shared/Components/Common/Toast/ToastStackView.swift, xcode/Subconscious/Shared/Components/Common/Toast/ToastView.swift, xcode/Subconscious/Shared/Components/Common/Transclude/TranscludeButtonStyle.swift, xcode/Subconscious/Shared/Components/Common/Transclude/TranscludeListView.swift, xcode/Subconscious/Shared/Components/Common/Transclude/TranscludeView.swift, xcode/Subconscious/Shared/Components/Deck/CardStackView.swift, xcode/Subconscious/Shared/Components/Deck/DeckNavigationView.swift, xcode/Subconscious/Shared/Components/Deck/DeckTheme.swift, xcode/Subconscious/Shared/Components/Deck/DeckView.swift, xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift, xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift, xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift, xcode/Subconscious/Shared/Components/Feed/Feed.swift, xcode/Subconscious/Shared/Components/HomeProfileView.swift, xcode/Subconscious/Shared/Components/MainToolbar.swift, xcode/Subconscious/Shared/Components/Notebook/Notebook.swift, xcode/Subconscious/Shared/Components/Notebook/NotebookNavigationView.swift, xcode/Subconscious/Shared/Components/OmniboxView.swift, xcode/Subconscious/Shared/Parsers/SubtextAttributedStringRenderer.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
Fixes https://github.com/subconsciousnetwork/subconscious/issues/1005
Fixes #988 
<br>
=> First steps toward implementing uniform app styles

xcode/Subconscious/Shared/Components/AppView.swift, xcode/Subconscious/Shared/Components/Common/AppendLinkSuggestionLabelView.swift, xcode/Subconscious/Shared/Components/Deck/DeckView.swift, xcode/Subconscious/Shared/Components/Detail/AppendLinkSearchView.swift, xcode/Subconscious/Shared/Components/Detail/DetailStackView.swift, xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift, xcode/Subconscious/Shared/Components/Detail/MemoEditorDetailMetaSheetView.swift, xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailMetaSheetView.swift, xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift, xcode/Subconscious/Shared/Components/HomeProfileView.swift, xcode/Subconscious/Shared/Components/Notebook/Notebook.swift, xcode/Subconscious/Shared/Models/AppendLinkSuggestion.swift, xcode/Subconscious/Shared/Services/DataService.swift, xcode/Subconscious/Shared/Services/DatabaseService.swift, xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj, xcode/Subconscious/SubconsciousTests/Tests_DataService.swift, xcode/Subconscious/SubconsciousTests/Tests_DeckDetailStackCursor.swift, xcode/Subconscious/SubconsciousTests/Tests_HomeProfileDetailStackCursor.swift, xcode/Subconscious/SubconsciousTests/Tests_MemoViewerDetailMetaSheet.swift, xcode/Subconscious/SubconsciousTests/Tests_NotebookDetailStackCursor.swift
Easily append a link to a note you're viewing to another note, useful for "bookmarking" behaviour.
https://github.com/subconsciousnetwork/subconscious/assets/5009316/7234109a-3517-4d58-96f3-e91819a81156
=> "Append link" action

xcode/Subconscious/Shared/Components/Deck/Cards/PromptCardView.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/1088
=> Fix line wrapping on Card prompts

xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/1102
=> Fall back to `ThemeColor.a` in editor if there's no slug

xcode/Subconscious/Shared/Components/Common/Profile/Sheets/FollowNewUserFormSheet.swift, xcode/Subconscious/Shared/Components/Discover/DiscoverView.swift, xcode/Subconscious/Shared/Services/DatabaseService.swift, xcode/Subconscious/SubconsciousTests/Tests_DatabaseService.swift
Self-explanatory 🤦 
I've added a test case that ensures we exclude ourselves from the list of users to discover.
=> Exclude ourselves from the list of users to discover

.github/workflows/run_test_suite_ios17.yaml
=> Introduce macOS 13 runner with iOS 17

xcode/Subconscious/Shared/Components/Common/AppendLinkSuggestionLabelView.swift, xcode/Subconscious/Shared/Library/DummyDataUtilities.swift, xcode/Subconscious/Shared/Models/Entry.swift, xcode/Subconscious/Shared/UIKit/BlockEditor/BlockEditorModel.swift
=> Fix various minor XCode warnings

xcode/Subconscious/Shared/Components/HomeProfileView.swift, xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
Fixes https://github.com/subconsciousnetwork/subconscious/issues/1136
=> Add missing mappings for "Append to Note" action
